export const CHAPTER_ONE_STORY_LABELS = Object.freeze({
  "zh-CN": { entry: "第一章 · 第一次开机", resume: "继续第一章", mode: "正式剧情", saved: "进度自动保存", back: "返回管理中心", enter: "进入电台 · 亲自发报", hint: "接下来使用真实电键完成 CQ、呼号和 RST 交换，再保存通联。对方可能复问，也可能没有回应；重试不会跳过这些步骤。", recorded: "以下是这次正式保存的通联记录。", finish: "完成第一章 · 领取任务奖励", complete: "第一章已完成，第二章已开放。", unavailable: "请从任务中心接受第一章；已有旧任务可在任务中心领取。", reward: "任务奖励只领取一次；通联收入已在保存日志时结算。" },
  "zh-TW": { entry: "第一章 · 第一次開機", resume: "繼續第一章", mode: "正式劇情", saved: "進度自動儲存", back: "返回管理中心", enter: "進入電臺 · 親自發報", hint: "接下來以真實電鍵完成 CQ、呼號和 RST 交換，再儲存通聯。對方可能複問或沒有回應；重試不會跳過這些步驟。", recorded: "以下是這次正式儲存的通聯紀錄。", finish: "完成第一章 · 領取任務獎勵", complete: "第一章已完成，第二章已開放。", unavailable: "請從任務中心接受第一章；既有舊任務可在任務中心領取。", reward: "任務獎勵只領取一次；通聯收入已於儲存日誌時結算。" },
  en: { entry: "Chapter One · First Power-On", resume: "Continue Chapter One", mode: "Story", saved: "Progress saved automatically", back: "Back to management", enter: "Enter station · key the call", hint: "Use the real key to exchange CQ, callsigns and RST, then save the contact. A station may ask for a repeat or remain silent; retrying does not skip the radio exchange.", recorded: "This is the contact saved in your actual log.", finish: "Complete Chapter One · claim reward", complete: "Chapter One complete. Chapter Two is available.", unavailable: "Accept Chapter One in Mission Center. Existing legacy tasks can still be claimed there.", reward: "Claim the mission reward once. QSO income was already settled when you saved the log." },
  ja: { entry: "第1章 · 初めての電源", resume: "第1章を続ける", mode: "ストーリー", saved: "進行状況は自動保存", back: "管理センターへ", enter: "無線機へ · 自分で送信", hint: "実際の電鍵で CQ、呼出符号、RST を交換し、交信を保存します。再送を求められたり、応答がなかったりすることもあります。再試行でも交信手順は省略されません。", recorded: "実際のログに保存した交信です。", finish: "第1章を完了 · 報酬を受け取る", complete: "第1章完了。第2章が開放されました。", unavailable: "ミッションセンターで第1章を受注してください。旧ミッションの報酬もそこで受け取れます。", reward: "ミッション報酬は一度だけです。交信収入はログ保存時に精算済みです。" },
  es: { entry: "Capítulo uno · Primer encendido", resume: "Continuar el capítulo uno", mode: "Historia", saved: "Progreso guardado automáticamente", back: "Volver a gestión", enter: "Entrar a la estación · transmitir", hint: "Usa la llave real para intercambiar CQ, indicativos y RST, y guarda el contacto. La estación puede pedir una repetición o no responder; reintentar no omite el intercambio.", recorded: "Este contacto está guardado en tu registro real.", finish: "Completar el capítulo uno · cobrar", complete: "Capítulo uno completado. Capítulo dos disponible.", unavailable: "Acepta el capítulo uno en el Centro de misiones. Las misiones antiguas también se cobran allí.", reward: "La recompensa se cobra una vez. El ingreso del QSO ya se liquidó al guardar el registro." },
  de: { entry: "Kapitel eins · Erstes Einschalten", resume: "Kapitel eins fortsetzen", mode: "Geschichte", saved: "Fortschritt automatisch gespeichert", back: "Zur Verwaltung", enter: "Zur Station · selbst senden", hint: "Tausche mit der echten Taste CQ, Rufzeichen und RST aus und speichere den Kontakt. Die Gegenstation kann um Wiederholung bitten oder schweigen; ein neuer Versuch überspringt keinen Austausch.", recorded: "Dieser Kontakt steht in deinem gespeicherten Log.", finish: "Kapitel eins abschließen · Belohnung", complete: "Kapitel eins abgeschlossen. Kapitel zwei ist verfügbar.", unavailable: "Nimm Kapitel eins im Missionszentrum an. Ältere Missionen können dort weiterhin abgerechnet werden.", reward: "Die Missionsbelohnung gibt es einmal. Der QSO-Ertrag wurde beim Speichern bereits abgerechnet." },
  ru: { entry: "Глава первая · Первое включение", resume: "Продолжить первую главу", mode: "История", saved: "Прогресс сохраняется автоматически", back: "В центр управления", enter: "На станцию · передать самому", hint: "Настоящим ключом передайте CQ, позывные и RST, затем сохраните связь. Станция может запросить повтор или промолчать; новая попытка не пропускает обмен.", recorded: "Эта связь сохранена в вашем настоящем журнале.", finish: "Завершить главу · получить награду", complete: "Первая глава завершена. Вторая глава доступна.", unavailable: "Примите первую главу в центре заданий. Старые задания по-прежнему можно завершить там.", reward: "Награда за задание выдаётся один раз. Доход за QSO уже начислен при сохранении журнала." },
});

export function chapterOneStoryLabels(language) {
  return CHAPTER_ONE_STORY_LABELS[language] ?? CHAPTER_ONE_STORY_LABELS.en;
}
