import { CONTEST_PHASES } from "../game/contestRun.js";

export { SETTLEMENT_SAVED_TEXT as CONTEST_SETTLED_TEXT } from "./settlementText.js";

const en = Object.freeze({
  title: "Crowded Air", kicker: "Chapter 10 · Five-minute contest", simulationWarning: "Fictional offline training contest. No real event, brand, or online ranking is used.", leave: "Leave", paused: "Contest clock paused while settings are open or the window is inactive.",
  controller: "Contest control", remaining: "Remaining", score: "Score", contacts: "Contacts", regions: "Regions", grade: "Grade", briefing: "Work both RUN and S&P in one five-minute session. Copy each frozen station and send its exact RST, serial, region, and power.",
  runMode: "RUN", spMode: "S&P", beginRun: "Start in RUN", beginSp: "Start in S&P", chooseMode: "Choose operating mode", pileup: "Frozen pile-up", stationPool: "Frozen station pool", listen: "Listen to callers", candidatePrompt: "Key the target callsign, then press F2.", cqPrompt: "Key the full contest CQ before callers may answer.",
  exchange: "Contest exchange", exchangeHint: "Key the full frozen exchange", transmit: "Transmit · F2", clear: "Clear", agn: "AGN K · Repeat", qrs: "QRS K · Slower", finish: "Finish run", needMinimum: "Finish after 6 contacts, 2 RUN, 2 S&P, and 3 regions.",
  validContacts: "Valid", cleanExchanges: "Clean", repeats: "Repeats", busted: "Busted", interruptions: "Interruptions", duplicate: "Duplicates", speed: "Reply speed", keyHintAutomatic: "Z · / X —", keyHintManual: "SPACE",
  completed: "Contest complete", failed: "Contest failed", retry: "Retry frozen contest", settle: "Save contest record", personalBest: "Personal best", noBest: "No saved best yet", leaveConfirm: "This contest is active or completed but unsaved. Leave anyway?", cancel: "Stay", confirmLeave: "Leave without saving",
  SEMANTIC_UNSAFE: "Semantic safety check rejected the transmission.", CQ_INVALID: "Send the complete contest CQ with your callsign.", INTERRUPTION: "Transmission interrupted the current caller.", CALLSIGN_MISMATCH: "The callsign does not match.", BUSTED_CALL: "That callsign is not in the frozen pool.", DUPLICATE_STATION: "That operator was already worked.", FORMAT_INVALID: "Use the complete labelled exchange in order.", RST_MISMATCH: "RST does not match the frozen station.", SERIAL_MISMATCH: "Serial number does not match.", REGION_MISMATCH: "Region does not match.", POWER_MISMATCH: "Power does not match.", MINIMUM_NOT_MET: "Minimum contact, mode, or region conditions were not met.", TIMED_OUT: "The five-minute contest window ended before the minimum was met.",
});

const CQ_COPY_BY_TITLE = Object.freeze({
  "空中的拥挤": { cqPrompt: "先用电键完整发出竞赛 CQ，来台才会应答。", CQ_INVALID: "请发出带本人呼号的完整竞赛 CQ。" },
  "空中的擁擠": { cqPrompt: "先用電鍵完整發出競賽 CQ，來臺才會應答。", CQ_INVALID: "請發出帶本人呼號的完整競賽 CQ。" },
  "混み合う空": { cqPrompt: "完全なコンテストCQを送信すると呼出局が応答します。", CQ_INVALID: "自局コールを含む完全なコンテストCQを送ってください。" },
  "Aire congestionado": { cqPrompt: "Telegrafía el CQ de concurso completo antes de recibir respuestas.", CQ_INVALID: "Envía el CQ de concurso completo con tu indicativo." },
  "Gedrängte Luft": { cqPrompt: "Erst den vollständigen Contest-CQ morsen, dann antworten Stationen.", CQ_INVALID: "Vollständigen Contest-CQ mit eigenem Rufzeichen senden." },
  "Тесный эфир": { cqPrompt: "Сначала передайте полный контест-вызов CQ, затем ответят станции.", CQ_INVALID: "Передайте полный контест-вызов CQ со своим позывным." },
});

function localized(overrides) { return Object.freeze({ ...en, ...overrides, ...(CQ_COPY_BY_TITLE[overrides.title] ?? {}) }); }

export const CONTEST_TEXT = Object.freeze({
  "zh-CN": localized({ title: "空中的拥挤", kicker: "第 10 章 · 五分钟短赛", simulationWarning: "这是虚构的离线训练比赛，不使用现实赛事、品牌或联网排名。", leave: "离开", paused: "设置开启或窗口失焦时，比赛时钟暂停。", controller: "比赛主控", remaining: "剩余", score: "得分", contacts: "联系人", regions: "地区", grade: "成绩", briefing: "在同一轮完成 RUN 与 S&P。抄准冻结台站，并发送完整的 RST、序号、地区和功率。", runMode: "RUN 主叫", spMode: "S&P 搜台", beginRun: "以 RUN 开始", beginSp: "以 S&P 开始", chooseMode: "选择操作模式", pileup: "冻结 pile-up", stationPool: "冻结台池", listen: "收听来台", candidatePrompt: "用电键发送目标呼号，再按 F2。", exchange: "比赛交换", exchangeHint: "用电键发送完整冻结交换", transmit: "发射 · F2", clear: "清空", agn: "AGN K · 重发", qrs: "QRS K · 降速", finish: "结束本轮", needMinimum: "至少完成6台、RUN与S&P各2台、3个地区。", validContacts: "有效", cleanExchanges: "干净交换", repeats: "重发", busted: "抄错呼号", interruptions: "抢发", duplicate: "重复", speed: "回发速度", keyHintManual: "空格键", completed: "比赛完成", failed: "比赛失败", retry: "重试冻结比赛", settle: "保存比赛记录", personalBest: "个人最佳", noBest: "尚无最佳记录", leaveConfirm: "比赛仍在进行或尚未保存，仍要离开吗？", cancel: "继续比赛", confirmLeave: "不保存并离开", SEMANTIC_UNSAFE: "语义安全检查拒绝了本次发射。", INTERRUPTION: "你在当前来台结束前抢发。", CALLSIGN_MISMATCH: "呼号不匹配。", BUSTED_CALL: "冻结台池中没有这个呼号。", DUPLICATE_STATION: "该操作员已经完成过通联。", FORMAT_INVALID: "请按顺序发送完整标签交换。", RST_MISMATCH: "RST 与冻结事实不符。", SERIAL_MISMATCH: "比赛序号不符。", REGION_MISMATCH: "地区不符。", POWER_MISMATCH: "功率不符。", MINIMUM_NOT_MET: "联系人、模式或地区最低条件未达到。", TIMED_OUT: "五分钟结束时尚未达到最低条件。" }),
  "zh-TW": localized({ title: "空中的擁擠", kicker: "第 10 章 · 五分鐘短賽", simulationWarning: "這是虛構離線訓練比賽，不使用現實賽事、品牌或連線排名。", leave: "離開", paused: "設定開啟或視窗失焦時，比賽時鐘暫停。", controller: "比賽主控", remaining: "剩餘", score: "得分", contacts: "聯絡人", regions: "地區", grade: "成績", briefing: "在同一輪完成 RUN 與 S&P。抄準凍結臺站，發送完整 RST、序號、地區與功率。", runMode: "RUN 主叫", spMode: "S&P 搜臺", beginRun: "以 RUN 開始", beginSp: "以 S&P 開始", chooseMode: "選擇操作模式", pileup: "凍結 pile-up", stationPool: "凍結臺池", listen: "收聽來臺", candidatePrompt: "用電鍵發送目標呼號，再按 F2。", exchange: "比賽交換", exchangeHint: "用電鍵發送完整凍結交換", transmit: "發射 · F2", clear: "清空", agn: "AGN K · 重發", qrs: "QRS K · 降速", finish: "結束本輪", needMinimum: "至少完成6臺、RUN與S&P各2臺、3個地區。", validContacts: "有效", cleanExchanges: "乾淨交換", repeats: "重發", busted: "抄錯呼號", interruptions: "搶發", duplicate: "重複", speed: "回發速度", keyHintManual: "空白鍵", completed: "比賽完成", failed: "比賽失敗", retry: "重試凍結比賽", settle: "儲存比賽記錄", personalBest: "個人最佳", noBest: "尚無最佳記錄", leaveConfirm: "比賽仍在進行或尚未儲存，仍要離開嗎？", cancel: "繼續比賽", confirmLeave: "不儲存並離開", SEMANTIC_UNSAFE: "語意安全檢查拒絕本次發射。", INTERRUPTION: "你在目前來臺結束前搶發。", CALLSIGN_MISMATCH: "呼號不符。", BUSTED_CALL: "凍結臺池中沒有此呼號。", DUPLICATE_STATION: "該操作員已完成過通聯。", FORMAT_INVALID: "請依序發送完整標籤交換。", RST_MISMATCH: "RST 與凍結事實不符。", SERIAL_MISMATCH: "比賽序號不符。", REGION_MISMATCH: "地區不符。", POWER_MISMATCH: "功率不符。", MINIMUM_NOT_MET: "聯絡人、模式或地區最低條件未達。", TIMED_OUT: "五分鐘結束時尚未達到最低條件。" }),
  ja: localized({ title: "混み合う空", kicker: "第10章 · 5分コンテスト", simulationWarning: "架空のオフライン練習コンテストです。実在の大会、ブランド、オンライン順位は使用しません。", leave: "離れる", paused: "設定中またはフォーカス外では時計を一時停止します。", controller: "コンテスト管制", remaining: "残り", score: "得点", contacts: "交信", regions: "地域", grade: "成績", briefing: "同じラウンドで RUN と S&P を運用し、固定局の RST・連番・地域・電力を正確に送ります。", runMode: "RUN 呼出", spMode: "S&P 探索", beginRun: "RUNで開始", beginSp: "S&Pで開始", chooseMode: "運用モードを選択", pileup: "固定パイルアップ", stationPool: "固定局プール", listen: "呼出局を受信", candidatePrompt: "キーで対象コールを送り、F2を押します。", exchange: "コンテスト交換", exchangeHint: "完全な固定交換をキーで送信", transmit: "送信 · F2", clear: "消去", agn: "AGN K · 再送", qrs: "QRS K · 低速", finish: "運用終了", needMinimum: "6局、RUN/S&P各2局、3地域が必要です。", validContacts: "有効", cleanExchanges: "無修正", repeats: "再送", busted: "誤コール", interruptions: "割込み", duplicate: "重複", speed: "返信速度", keyHintManual: "SPACE", completed: "コンテスト完了", failed: "コンテスト失敗", retry: "固定コンテストを再試行", settle: "記録を保存", personalBest: "自己ベスト", noBest: "保存済み記録なし", leaveConfirm: "進行中または未保存です。離れますか？", cancel: "続ける", confirmLeave: "保存せず離れる", SEMANTIC_UNSAFE: "意味安全チェックで送信が拒否されました。", INTERRUPTION: "呼出局の終了前に割り込みました。", CALLSIGN_MISMATCH: "コールサインが一致しません。", BUSTED_CALL: "固定局プールにないコールです。", DUPLICATE_STATION: "このオペレーターとは交信済みです。", FORMAT_INVALID: "ラベル付き交換を正しい順序で送ってください。", RST_MISMATCH: "RSTが固定情報と一致しません。", SERIAL_MISMATCH: "連番が一致しません。", REGION_MISMATCH: "地域が一致しません。", POWER_MISMATCH: "電力が一致しません。", MINIMUM_NOT_MET: "交信数、モード、地域の最低条件未達です。", TIMED_OUT: "5分以内に最低条件を満たせませんでした。" }),
  en,
  es: localized({ title: "Aire congestionado", kicker: "Capítulo 10 · Concurso de cinco minutos", simulationWarning: "Concurso ficticio y sin conexión; no usa eventos, marcas ni clasificaciones reales.", leave: "Salir", paused: "El reloj se pausa con ajustes abiertos o sin foco.", controller: "Control del concurso", remaining: "Restante", score: "Puntos", contacts: "Contactos", regions: "Regiones", grade: "Resultado", briefing: "Trabaja RUN y S&P en la misma ronda y envía RST, número, región y potencia exactos.", runMode: "RUN llamada", spMode: "S&P búsqueda", beginRun: "Empezar en RUN", beginSp: "Empezar en S&P", chooseMode: "Elegir modo", pileup: "Pile-up fijo", stationPool: "Grupo fijo", listen: "Escuchar estaciones", candidatePrompt: "Telegrafía el indicativo y pulsa F2.", exchange: "Intercambio", exchangeHint: "Telegrafía el intercambio fijo completo", transmit: "Transmitir · F2", clear: "Borrar", agn: "AGN K · Repetir", qrs: "QRS K · Más lento", finish: "Terminar ronda", needMinimum: "Se requieren 6 contactos, 2 RUN, 2 S&P y 3 regiones.", validContacts: "Válidos", cleanExchanges: "Limpios", repeats: "Repeticiones", busted: "Indicativos erróneos", interruptions: "Interrupciones", duplicate: "Duplicados", speed: "Velocidad", keyHintManual: "ESPACIO", completed: "Concurso completado", failed: "Concurso fallido", retry: "Reintentar concurso", settle: "Guardar resultado", personalBest: "Mejor marca", noBest: "Aún no hay marca", leaveConfirm: "El concurso está activo o sin guardar. ¿Salir?", cancel: "Seguir", confirmLeave: "Salir sin guardar", SEMANTIC_UNSAFE: "La comprobación semántica rechazó la transmisión.", INTERRUPTION: "Transmitiste antes de acabar la estación actual.", CALLSIGN_MISMATCH: "El indicativo no coincide.", BUSTED_CALL: "El indicativo no está en el grupo fijo.", DUPLICATE_STATION: "Ese operador ya fue trabajado.", FORMAT_INVALID: "Usa el intercambio etiquetado completo y ordenado.", RST_MISMATCH: "El RST no coincide.", SERIAL_MISMATCH: "El número no coincide.", REGION_MISMATCH: "La región no coincide.", POWER_MISMATCH: "La potencia no coincide.", MINIMUM_NOT_MET: "No se cumplió el mínimo de contactos, modos o regiones.", TIMED_OUT: "Los cinco minutos acabaron antes del mínimo." }),
  de: localized({ title: "Gedrängte Luft", kicker: "Kapitel 10 · Fünf-Minuten-Contest", simulationWarning: "Fiktiver Offline-Übungscontest ohne reales Ereignis, Marke oder Online-Rangliste.", leave: "Verlassen", paused: "Bei Einstellungen oder Fokusverlust pausiert die Uhr.", controller: "Contest-Leitung", remaining: "Restzeit", score: "Punkte", contacts: "Kontakte", regions: "Regionen", grade: "Wertung", briefing: "Arbeite RUN und S&P in einer Runde und sende RST, Seriennummer, Region und Leistung exakt.", runMode: "RUN-Ruf", spMode: "S&P-Suche", beginRun: "Mit RUN starten", beginSp: "Mit S&P starten", chooseMode: "Betriebsart wählen", pileup: "Festes Pile-up", stationPool: "Fester Stationspool", listen: "Stationen hören", candidatePrompt: "Zielrufzeichen morsen, dann F2 drücken.", exchange: "Contest-Austausch", exchangeHint: "Vollständigen festen Austausch morsen", transmit: "Senden · F2", clear: "Löschen", agn: "AGN K · Wiederholen", qrs: "QRS K · Langsamer", finish: "Runde beenden", needMinimum: "Benötigt: 6 Kontakte, je 2 RUN/S&P und 3 Regionen.", validContacts: "Gültig", cleanExchanges: "Sauber", repeats: "Wiederholungen", busted: "Fehlruf", interruptions: "Unterbrechungen", duplicate: "Doppelte", speed: "Antworttempo", keyHintManual: "LEERTASTE", completed: "Contest abgeschlossen", failed: "Contest fehlgeschlagen", retry: "Festen Contest wiederholen", settle: "Ergebnis speichern", personalBest: "Bestleistung", noBest: "Noch keine Bestleistung", leaveConfirm: "Contest aktiv oder ungespeichert. Verlassen?", cancel: "Bleiben", confirmLeave: "Ohne Speichern verlassen", SEMANTIC_UNSAFE: "Die semantische Prüfung wies die Sendung ab.", INTERRUPTION: "Du hast vor Ende der rufenden Station gesendet.", CALLSIGN_MISMATCH: "Rufzeichen stimmt nicht.", BUSTED_CALL: "Rufzeichen fehlt im festen Pool.", DUPLICATE_STATION: "Dieser Operator wurde schon gearbeitet.", FORMAT_INVALID: "Vollständigen markierten Austausch geordnet senden.", RST_MISMATCH: "RST stimmt nicht.", SERIAL_MISMATCH: "Seriennummer stimmt nicht.", REGION_MISMATCH: "Region stimmt nicht.", POWER_MISMATCH: "Leistung stimmt nicht.", MINIMUM_NOT_MET: "Mindestzahl, Betriebsarten oder Regionen fehlen.", TIMED_OUT: "Fünf Minuten endeten vor Erreichen des Minimums." }),
  ru: localized({ title: "Тесный эфир", kicker: "Глава 10 · Пятиминутный контест", simulationWarning: "Вымышленный автономный учебный контест без реального события, бренда или сетевого рейтинга.", leave: "Выйти", paused: "Таймер остановлен при настройках или потере фокуса.", controller: "Управление контестом", remaining: "Осталось", score: "Очки", contacts: "Связи", regions: "Регионы", grade: "Результат", briefing: "Проведите RUN и S&P в одном туре и точно передайте RST, номер, регион и мощность.", runMode: "RUN вызов", spMode: "S&P поиск", beginRun: "Начать RUN", beginSp: "Начать S&P", chooseMode: "Выбрать режим", pileup: "Фиксированный пайлап", stationPool: "Фиксированный пул", listen: "Слушать станции", candidatePrompt: "Передайте позывной ключом и нажмите F2.", exchange: "Обмен контеста", exchangeHint: "Передайте полный фиксированный обмен", transmit: "Передать · F2", clear: "Очистить", agn: "AGN K · Повтор", qrs: "QRS K · Медленнее", finish: "Завершить тур", needMinimum: "Нужно 6 связей, по 2 RUN/S&P и 3 региона.", validContacts: "Зачтено", cleanExchanges: "Чисто", repeats: "Повторы", busted: "Ошибки позывного", interruptions: "Перебивания", duplicate: "Дубли", speed: "Скорость ответа", keyHintManual: "ПРОБЕЛ", completed: "Контест завершён", failed: "Контест не пройден", retry: "Повторить фиксированный контест", settle: "Сохранить результат", personalBest: "Личный рекорд", noBest: "Рекорда пока нет", leaveConfirm: "Контест идёт или не сохранён. Выйти?", cancel: "Продолжить", confirmLeave: "Выйти без сохранения", SEMANTIC_UNSAFE: "Смысловая проверка отклонила передачу.", INTERRUPTION: "Передача началась до конца вызывающей станции.", CALLSIGN_MISMATCH: "Позывной не совпадает.", BUSTED_CALL: "Позывного нет в фиксированном пуле.", DUPLICATE_STATION: "Этот оператор уже сработан.", FORMAT_INVALID: "Передайте полный обмен с метками по порядку.", RST_MISMATCH: "RST не совпадает.", SERIAL_MISMATCH: "Номер не совпадает.", REGION_MISMATCH: "Регион не совпадает.", POWER_MISMATCH: "Мощность не совпадает.", MINIMUM_NOT_MET: "Не выполнен минимум связей, режимов или регионов.", TIMED_OUT: "Пять минут закончились до выполнения минимума." }),
});

export function contestLeaveRisk(run, settled = false) {
  if (settled || !run || [CONTEST_PHASES.FAILED, CONTEST_PHASES.ABANDONED].includes(run.phase)) return "none";
  return run.phase === CONTEST_PHASES.COMPLETED ? "unsaved" : "active";
}
