import { COORDINATE_RELAY_PHASES } from "../game/coordinateRelayRun.js";

const en = {
  title: "Coordinate Relay", kicker: "Chapter 09 · Pixel Grid", simulationWarning: "Fictional training grid. It is not a real location or emergency service.", leave: "Leave", paused: "Paused while settings or another window has focus.",
  source: "Source station", relay: "Relay station", packet: "Frozen packet", messageId: "Message", grid: "Pixel Grid", utc: "UTC", people: "People", check: "Check", elapsed: "Elapsed",
  briefing: "Copy one frozen coordinate packet from SIM9CR, read every field back, then relay the same packet to SIM9RL.", begin: "Begin relay", receive: "Copy packet", readback: "Read back to source", relayPacket: "Send to relay", confirmation: "Relay confirmation", hint: "Enter the complete canonical packet", send: "Transmit", agn: "AGN · Repeat", qrs: "QRS · Slower", attempts: "Readback attempts",
  completed: "Coordinate relay complete", settle: "Save relay record", failed: "Relay failed", retry: "Retry frozen packet", leaveConfirm: "This relay is still active or has not been saved. Leave anyway?", cancel: "Stay", confirmLeave: "Leave without saving",
  MESSAGE_ID_MISMATCH: "Message number does not match.", GRID_MISMATCH: "Pixel Grid field does not match.", TIME_MISMATCH: "UTC field does not match.", PEOPLE_MISMATCH: "People field does not match.", CHECK_MISMATCH: "Computed check does not match.", FORMAT_INVALID: "Use the labelled canonical field order.", SEMANTIC_UNSAFE: "The transmission could not be safely committed.", RELAY_CONFIRMATION_INVALID: "Relay confirmation is invalid.", TOO_MANY_ERRORS: "Three complete readbacks failed.", TIMED_OUT: "The ten-minute relay window ended.",
};

function localized(overrides) { return Object.freeze({ ...en, ...overrides }); }

export const COORDINATE_RELAY_TEXT = Object.freeze({
  "zh-CN": localized({ title: "坐标中继", kicker: "第 09 章 · 像素网格", simulationWarning: "这是虚构训练网格，不代表真实地点或应急服务。", leave: "离开", paused: "设置开启或窗口失焦时暂停。", source: "源台", relay: "中继台", packet: "冻结报文", messageId: "报文号", grid: "像素网格", utc: "UTC 时间", people: "人数", check: "校验", elapsed: "用时", briefing: "从 SIM9CR 抄收一条冻结坐标报文，完整读回，再把同一报文中继给 SIM9RL。", begin: "开始中继", receive: "抄收报文", readback: "向源台读回", relayPacket: "发送给中继台", confirmation: "中继确认", hint: "输入完整规范报文", send: "发射", agn: "AGN · 重发", qrs: "QRS · 降速", attempts: "读回次数", completed: "坐标中继完成", settle: "保存中继记录", failed: "中继失败", retry: "重试冻结报文", leaveConfirm: "本轮仍在进行或尚未保存。仍要离开吗？", cancel: "继续", confirmLeave: "不保存并离开", MESSAGE_ID_MISMATCH: "报文编号不匹配。", GRID_MISMATCH: "像素网格字段不匹配。", TIME_MISMATCH: "UTC 时间不匹配。", PEOPLE_MISMATCH: "人数字段不匹配。", CHECK_MISMATCH: "计算校验不匹配。", FORMAT_INVALID: "请按标签顺序发送规范字段。", SEMANTIC_UNSAFE: "该发射无法安全提交。", RELAY_CONFIRMATION_INVALID: "中继确认无效。", TOO_MANY_ERRORS: "三次完整读回均失败。", TIMED_OUT: "十分钟中继窗口已结束。" }),
  "zh-TW": localized({ title: "座標中繼", kicker: "第 09 章 · 像素網格", simulationWarning: "這是虛構訓練網格，不代表真實地點或緊急服務。", leave: "離開", paused: "設定開啟或視窗失焦時暫停。", source: "來源臺", relay: "中繼臺", packet: "凍結報文", messageId: "報文號", grid: "像素網格", utc: "UTC 時間", people: "人數", check: "校驗", elapsed: "用時", briefing: "從 SIM9CR 抄收凍結座標報文，完整讀回，再將同一報文中繼給 SIM9RL。", begin: "開始中繼", receive: "抄收報文", readback: "向來源臺讀回", relayPacket: "發送給中繼臺", confirmation: "中繼確認", hint: "輸入完整規範報文", send: "發射", agn: "AGN · 重發", qrs: "QRS · 降速", attempts: "讀回次數", completed: "座標中繼完成", settle: "儲存中繼記錄", failed: "中繼失敗", retry: "重試凍結報文", leaveConfirm: "本輪仍在進行或尚未儲存。仍要離開嗎？", cancel: "繼續", confirmLeave: "不儲存並離開", MESSAGE_ID_MISMATCH: "報文編號不符。", GRID_MISMATCH: "像素網格欄位不符。", TIME_MISMATCH: "UTC 時間不符。", PEOPLE_MISMATCH: "人數欄位不符。", CHECK_MISMATCH: "計算校驗不符。", FORMAT_INVALID: "請依標籤順序發送規範欄位。", SEMANTIC_UNSAFE: "此發射無法安全提交。", RELAY_CONFIRMATION_INVALID: "中繼確認無效。", TOO_MANY_ERRORS: "三次完整讀回皆失敗。", TIMED_OUT: "十分鐘中繼時限已結束。" }),
  ja: localized({ title: "座標リレー", kicker: "第09章 · ピクセルグリッド", simulationWarning: "架空の訓練グリッドです。実在の場所や緊急サービスではありません。", leave: "離れる", paused: "設定中またはフォーカス外では一時停止します。", source: "送信元局", relay: "中継局", packet: "固定パケット", messageId: "電文番号", grid: "ピクセルグリッド", utc: "UTC", people: "人数", check: "チェック", elapsed: "経過", briefing: "SIM9CR の固定座標電文を受信し、全項目を復唱してから同じ電文を SIM9RL へ中継します。", begin: "中継開始", receive: "電文を受信", readback: "送信元へ復唱", relayPacket: "中継局へ送信", confirmation: "中継確認", hint: "完全な標準電文を入力", send: "送信", agn: "AGN · 再送", qrs: "QRS · 減速", attempts: "復唱回数", completed: "座標リレー完了", settle: "記録を保存", failed: "中継失敗", retry: "固定電文を再試行", leaveConfirm: "中継が進行中または未保存です。離れますか？", cancel: "続ける", confirmLeave: "保存せず離れる", MESSAGE_ID_MISMATCH: "電文番号が一致しません。", GRID_MISMATCH: "グリッド項目が一致しません。", TIME_MISMATCH: "UTC項目が一致しません。", PEOPLE_MISMATCH: "人数項目が一致しません。", CHECK_MISMATCH: "計算チェックが一致しません。", FORMAT_INVALID: "ラベル付き標準順序で送信してください。", SEMANTIC_UNSAFE: "安全に確定できない送信です。", RELAY_CONFIRMATION_INVALID: "中継確認が無効です。", TOO_MANY_ERRORS: "三回の完全復唱に失敗しました。", TIMED_OUT: "10分の中継時間が終了しました。" }),
  en: Object.freeze(en),
  es: localized({ title: "Relevo de coordenadas", kicker: "Capítulo 09 · Cuadrícula Pixel", simulationWarning: "Cuadrícula ficticia de entrenamiento; no representa lugares ni emergencias reales.", leave: "Salir", paused: "Pausado con ajustes abiertos o sin foco.", source: "Estación de origen", relay: "Estación de relevo", packet: "Paquete fijo", messageId: "Mensaje", grid: "Cuadrícula Pixel", utc: "UTC", people: "Personas", check: "Control", elapsed: "Tiempo", briefing: "Copia el paquete fijo de SIM9CR, repite todos los campos y relévalo a SIM9RL.", begin: "Iniciar relevo", receive: "Copiar paquete", readback: "Repetir al origen", relayPacket: "Enviar al relevo", confirmation: "Confirmación", hint: "Introduce el paquete canónico completo", send: "Transmitir", agn: "AGN · Repetir", qrs: "QRS · Más lento", attempts: "Intentos", completed: "Relevo completado", settle: "Guardar registro", failed: "Relevo fallido", retry: "Reintentar paquete", leaveConfirm: "El relevo sigue activo o sin guardar. ¿Salir?", cancel: "Seguir", confirmLeave: "Salir sin guardar", MESSAGE_ID_MISMATCH: "El número no coincide.", GRID_MISMATCH: "La cuadrícula no coincide.", TIME_MISMATCH: "La hora UTC no coincide.", PEOPLE_MISMATCH: "El número de personas no coincide.", CHECK_MISMATCH: "El control calculado no coincide.", FORMAT_INVALID: "Usa el orden canónico etiquetado.", SEMANTIC_UNSAFE: "La transmisión no se puede confirmar con seguridad.", RELAY_CONFIRMATION_INVALID: "Confirmación inválida.", TOO_MANY_ERRORS: "Fallaron tres lecturas completas.", TIMED_OUT: "Terminó la ventana de diez minutos." }),
  de: localized({ title: "Koordinatenrelais", kicker: "Kapitel 09 · Pixelraster", simulationWarning: "Fiktives Übungsraster; kein realer Ort oder Notfalldienst.", leave: "Verlassen", paused: "Bei Einstellungen oder Fokusverlust pausiert.", source: "Quellstation", relay: "Relaisstation", packet: "Festes Paket", messageId: "Nachricht", grid: "Pixelraster", utc: "UTC", people: "Personen", check: "Prüfwert", elapsed: "Zeit", briefing: "Nimm das feste Paket von SIM9CR auf, lies alle Felder zurück und leite es an SIM9RL weiter.", begin: "Relais starten", receive: "Paket aufnehmen", readback: "Zur Quelle zurücklesen", relayPacket: "Zum Relais senden", confirmation: "Relaisbestätigung", hint: "Vollständiges kanonisches Paket eingeben", send: "Senden", agn: "AGN · Wiederholen", qrs: "QRS · Langsamer", attempts: "Versuche", completed: "Koordinatenrelais abgeschlossen", settle: "Relais speichern", failed: "Relais fehlgeschlagen", retry: "Festes Paket erneut", leaveConfirm: "Relais aktiv oder ungespeichert. Trotzdem verlassen?", cancel: "Bleiben", confirmLeave: "Ohne Speichern verlassen", MESSAGE_ID_MISMATCH: "Nachrichtennummer stimmt nicht.", GRID_MISMATCH: "Pixelraster stimmt nicht.", TIME_MISMATCH: "UTC-Feld stimmt nicht.", PEOPLE_MISMATCH: "Personenzahl stimmt nicht.", CHECK_MISMATCH: "Berechneter Prüfwert stimmt nicht.", FORMAT_INVALID: "Nutze die markierte kanonische Reihenfolge.", SEMANTIC_UNSAFE: "Übertragung kann nicht sicher bestätigt werden.", RELAY_CONFIRMATION_INVALID: "Relaisbestätigung ist ungültig.", TOO_MANY_ERRORS: "Drei vollständige Rücklesungen schlugen fehl.", TIMED_OUT: "Das Zehn-Minuten-Fenster endete." }),
  ru: localized({ title: "Ретрансляция координат", kicker: "Глава 09 · Пиксельная сетка", simulationWarning: "Вымышленная учебная сетка; это не реальное место и не экстренная служба.", leave: "Выйти", paused: "Пауза при настройках или потере фокуса.", source: "Исходная станция", relay: "Релейная станция", packet: "Фиксированный пакет", messageId: "Сообщение", grid: "Пиксельная сетка", utc: "UTC", people: "Люди", check: "Проверка", elapsed: "Время", briefing: "Примите пакет от SIM9CR, повторите все поля и передайте тот же пакет SIM9RL.", begin: "Начать ретрансляцию", receive: "Принять пакет", readback: "Повторить источнику", relayPacket: "Передать на реле", confirmation: "Подтверждение", hint: "Введите полный канонический пакет", send: "Передать", agn: "AGN · Повтор", qrs: "QRS · Медленнее", attempts: "Попытки", completed: "Ретрансляция завершена", settle: "Сохранить запись", failed: "Ретрансляция не удалась", retry: "Повторить пакет", leaveConfirm: "Ретрансляция активна или не сохранена. Выйти?", cancel: "Остаться", confirmLeave: "Выйти без сохранения", MESSAGE_ID_MISMATCH: "Номер сообщения не совпадает.", GRID_MISMATCH: "Поле сетки не совпадает.", TIME_MISMATCH: "Время UTC не совпадает.", PEOPLE_MISMATCH: "Число людей не совпадает.", CHECK_MISMATCH: "Расчётная проверка не совпадает.", FORMAT_INVALID: "Используйте канонический порядок меток.", SEMANTIC_UNSAFE: "Передачу нельзя безопасно подтвердить.", RELAY_CONFIRMATION_INVALID: "Подтверждение реле неверно.", TOO_MANY_ERRORS: "Три полных повтора не удались.", TIMED_OUT: "Десятиминутное окно завершилось." }),
});

export function coordinateRelayLeaveRisk(run, settled) {
  if (settled || !run || [COORDINATE_RELAY_PHASES.ABANDONED, COORDINATE_RELAY_PHASES.FAILED].includes(run.phase)) return "none";
  return run.phase === COORDINATE_RELAY_PHASES.COMPLETED ? "unsaved" : "active";
}
