export const EXPEDITION_TEXT = {
  "zh-CN": { title: "山丘临时台", chooseSite: "选择虚构场地", loan: "借用套件", owned: "自有套件", ownedUnavailable: "当前没有完整的可用自有套件", antennaSetup: "架设天线", powerSetup: "连接电池", wrongSetup: "错误接线", callCq: "呼叫 CQ", receiveReply: "等待并抄收回应", exchange: "远征交换", exchangeHint: "必须发送 QTH、PWR 与 ANT", sendExchange: "发送交换", agn: "请求重发 AGN", qrs: "请求慢发 QRS", battery: "电池", propagation: "传播", noise: "噪声", result: "结果", settle: "收台结算", retry: "重新远征", leave: "返回管理中心", leaveConfirm: "当前远征尚未安全结束，确认离开？", cancel: "继续远征", confirmLeave: "确认离开", paused: "设置菜单已暂停远征", success: "远征通联完成", failed: "远征失败", siteSelection: "场地选择", setup: "架台", ready: "准备呼叫", calling: "CQ 呼叫中", recovering: "链路恢复", completed: "完成", requiredTopics: "必需内容", expeditionSiteSunward: "向阳丘", expeditionSiteCedarBreeze: "杉风丘", expeditionSiteLakeview: "望湖丘", failureInvalidWiring: "天线接线错误，时间与电量受损", failureInvalidAntenna: "天线配置错误，时间与电量受损", failureInvalidPower: "供电配置错误，时间与电量受损", failureWeakLink: "弱信号链路需要 AGN 或 QRS", failureExchange: "交换内容未抄收", failureRetries: "重试次数耗尽", failureTimeout: "时间耗尽", failurePower: "电池耗尽", failureSetup: "架台尝试耗尽", failureCorrupt: "远征数据无法验证" },
  "zh-TW": { title: "山丘臨時臺", chooseSite: "選擇虛構場地", loan: "借用套件", owned: "自有套件", ownedUnavailable: "目前沒有完整的可用自有套件", antennaSetup: "架設天線", powerSetup: "連接電池", wrongSetup: "錯誤接線", callCq: "呼叫 CQ", receiveReply: "等待並抄收回應", exchange: "遠征交換", exchangeHint: "必須發送 QTH、PWR 與 ANT", sendExchange: "發送交換", agn: "請求重發 AGN", qrs: "請求慢發 QRS", battery: "電池", propagation: "傳播", noise: "雜訊", result: "結果", settle: "收臺結算", retry: "重新遠征", leave: "返回管理中心", leaveConfirm: "目前遠征尚未安全結束，確認離開？", cancel: "繼續遠征", confirmLeave: "確認離開", paused: "設定選單已暫停遠征", success: "遠征通聯完成", failed: "遠征失敗", siteSelection: "場地選擇", setup: "架臺", ready: "準備呼叫", calling: "CQ 呼叫中", recovering: "鏈路恢復", completed: "完成", requiredTopics: "必要內容", expeditionSiteSunward: "向陽丘", expeditionSiteCedarBreeze: "杉風丘", expeditionSiteLakeview: "望湖丘", failureInvalidWiring: "天線接線錯誤，時間與電量受損", failureInvalidAntenna: "天線配置錯誤，時間與電量受損", failureInvalidPower: "供電配置錯誤，時間與電量受損", failureWeakLink: "弱訊號鏈路需要 AGN 或 QRS", failureExchange: "交換內容未抄收", failureRetries: "重試次數耗盡", failureTimeout: "時間耗盡", failurePower: "電池耗盡", failureSetup: "架臺嘗試耗盡", failureCorrupt: "遠征資料無法驗證" },
  ja: { title: "丘の移動運用", chooseSite: "架空の運用地を選択", loan: "貸出セット", owned: "所有セット", ownedUnavailable: "使用可能な所有セットはまだ揃っていません", antennaSetup: "アンテナ設営", powerSetup: "バッテリー接続", wrongSetup: "誤配線", callCq: "CQ を送信", receiveReply: "応答を待って受信", exchange: "移動運用交換", exchangeHint: "QTH・PWR・ANT が必要", sendExchange: "交換を送信", agn: "AGN で再送依頼", qrs: "QRS で低速依頼", battery: "バッテリー", propagation: "伝搬", noise: "ノイズ", result: "結果", settle: "撤収・精算", retry: "再挑戦", leave: "管理センターへ", leaveConfirm: "運用は安全に終了していません。退出しますか？", cancel: "運用を続ける", confirmLeave: "退出する", paused: "設定メニューで運用を一時停止中", success: "移動運用 QSO 成功", failed: "移動運用失敗", siteSelection: "運用地選択", setup: "設営", ready: "呼出準備", calling: "CQ 呼出中", recovering: "回線回復", completed: "完了", requiredTopics: "必須項目", expeditionSiteSunward: "日向丘", expeditionSiteCedarBreeze: "杉風丘", expeditionSiteLakeview: "湖望丘", failureInvalidWiring: "アンテナ誤配線で時間と電力を消費", failureInvalidAntenna: "アンテナ設定不良で時間と電力を消費", failureInvalidPower: "電源設定不良で時間と電力を消費", failureWeakLink: "弱い回線には AGN または QRS が必要", failureExchange: "交換を受信できません", failureRetries: "再試行回数を超過", failureTimeout: "時間切れ", failurePower: "バッテリー切れ", failureSetup: "設営試行を超過", failureCorrupt: "運用データを検証できません" },
  en: { title: "Hilltop Field Station", chooseSite: "Choose a fictional field site", loan: "Loan kit", owned: "Owned kit", ownedUnavailable: "No complete owned field kit is currently available", antennaSetup: "Raise antenna", powerSetup: "Connect battery", wrongSetup: "Wrong setup", callCq: "Call CQ", receiveReply: "Wait for and copy reply", exchange: "Expedition exchange", exchangeHint: "Send QTH, PWR and ANT", sendExchange: "Send exchange", agn: "Request repeat — AGN", qrs: "Request slower sending — QRS", battery: "Battery", propagation: "Propagation", noise: "Noise", result: "Result", settle: "Close station and settle", retry: "Retry expedition", leave: "Return to Management Center", leaveConfirm: "This expedition is not safely finished. Leave anyway?", cancel: "Continue expedition", confirmLeave: "Leave expedition", paused: "Expedition paused by settings menu", success: "Expedition contact completed", failed: "Expedition failed", siteSelection: "Site selection", setup: "Station setup", ready: "Ready to call", calling: "Calling CQ", recovering: "Link recovery", completed: "Completed", requiredTopics: "Required topics", expeditionSiteSunward: "Sunward Hill", expeditionSiteCedarBreeze: "Cedar Breeze Hill", expeditionSiteLakeview: "Lakeview Hill", failureInvalidWiring: "Wrong antenna wiring cost time and battery", failureInvalidAntenna: "Wrong antenna setup cost time and battery", failureInvalidPower: "Wrong power setup cost time and battery", failureWeakLink: "Weak link needs AGN or QRS", failureExchange: "Exchange was not copied", failureRetries: "Retry limit reached", failureTimeout: "Time expired", failurePower: "Battery depleted", failureSetup: "Setup attempts exhausted", failureCorrupt: "Expedition data could not be verified" },
  es: { title: "Estación portátil en la colina", chooseSite: "Elige un lugar ficticio", loan: "Equipo prestado", owned: "Equipo propio", ownedUnavailable: "Aún no hay un equipo propio completo disponible", antennaSetup: "Montar antena", powerSetup: "Conectar batería", wrongSetup: "Montaje incorrecto", callCq: "Llamar CQ", receiveReply: "Esperar y copiar respuesta", exchange: "Intercambio de expedición", exchangeHint: "Envía QTH, PWR y ANT", sendExchange: "Enviar intercambio", agn: "Pedir repetición — AGN", qrs: "Pedir menor velocidad — QRS", battery: "Batería", propagation: "Propagación", noise: "Ruido", result: "Resultado", settle: "Cerrar y liquidar", retry: "Reintentar expedición", leave: "Volver al Centro de Gestión", leaveConfirm: "La expedición no ha terminado de forma segura. ¿Salir?", cancel: "Continuar expedición", confirmLeave: "Salir", paused: "Expedición pausada por el menú", success: "Contacto de expedición completado", failed: "Expedición fallida", siteSelection: "Selección del lugar", setup: "Montaje", ready: "Listo para llamar", calling: "Llamando CQ", recovering: "Recuperación del enlace", completed: "Completado", requiredTopics: "Temas requeridos", expeditionSiteSunward: "Colina Soleada", expeditionSiteCedarBreeze: "Colina Brisa de Cedro", expeditionSiteLakeview: "Colina Miralago", failureInvalidWiring: "El cableado erróneo consumió tiempo y batería", failureInvalidAntenna: "La antena errónea consumió tiempo y batería", failureInvalidPower: "La alimentación errónea consumió tiempo y batería", failureWeakLink: "El enlace débil necesita AGN o QRS", failureExchange: "No se copió el intercambio", failureRetries: "Límite de reintentos alcanzado", failureTimeout: "Tiempo agotado", failurePower: "Batería agotada", failureSetup: "Intentos de montaje agotados", failureCorrupt: "No se pudieron verificar los datos" },
  de: { title: "Feldstation auf dem Hügel", chooseSite: "Fiktiven Standort wählen", loan: "Leihsatz", owned: "Eigener Satz", ownedUnavailable: "Noch ist kein vollständiger eigener Feldsatz verfügbar", antennaSetup: "Antenne aufbauen", powerSetup: "Batterie anschließen", wrongSetup: "Falscher Aufbau", callCq: "CQ rufen", receiveReply: "Antwort abwarten und aufnehmen", exchange: "Expeditionsaustausch", exchangeHint: "QTH, PWR und ANT senden", sendExchange: "Austausch senden", agn: "Wiederholung anfordern — AGN", qrs: "Langsamer anfordern — QRS", battery: "Batterie", propagation: "Ausbreitung", noise: "Rauschen", result: "Ergebnis", settle: "Station schließen und abrechnen", retry: "Expedition wiederholen", leave: "Zur Verwaltungszentrale", leaveConfirm: "Die Expedition ist nicht sicher beendet. Trotzdem verlassen?", cancel: "Expedition fortsetzen", confirmLeave: "Verlassen", paused: "Expedition durch Einstellungen pausiert", success: "Expeditions-QSO abgeschlossen", failed: "Expedition fehlgeschlagen", siteSelection: "Standortwahl", setup: "Stationsaufbau", ready: "Rufbereit", calling: "CQ-Ruf", recovering: "Verbindung wiederherstellen", completed: "Abgeschlossen", requiredTopics: "Pflichtthemen", expeditionSiteSunward: "Sonnenhang", expeditionSiteCedarBreeze: "Zedernwindhügel", expeditionSiteLakeview: "Seeblickhügel", failureInvalidWiring: "Falsche Antennenverkabelung kostete Zeit und Energie", failureInvalidAntenna: "Falscher Antennenaufbau kostete Zeit und Energie", failureInvalidPower: "Falsche Stromversorgung kostete Zeit und Energie", failureWeakLink: "Schwache Verbindung braucht AGN oder QRS", failureExchange: "Austausch wurde nicht aufgenommen", failureRetries: "Wiederholungslimit erreicht", failureTimeout: "Zeit abgelaufen", failurePower: "Batterie leer", failureSetup: "Aufbauversuche aufgebraucht", failureCorrupt: "Expeditionsdaten konnten nicht geprüft werden" },
  ru: { title: "Полевая станция на холме", chooseSite: "Выберите вымышленную площадку", loan: "Комплект напрокат", owned: "Свой комплект", ownedUnavailable: "Полного собственного полевого комплекта пока нет", antennaSetup: "Установить антенну", powerSetup: "Подключить батарею", wrongSetup: "Ошибочная настройка", callCq: "Передать CQ", receiveReply: "Ждать и принять ответ", exchange: "Полевой обмен", exchangeHint: "Передайте QTH, PWR и ANT", sendExchange: "Передать обмен", agn: "Запросить повтор — AGN", qrs: "Запросить медленнее — QRS", battery: "Батарея", propagation: "Прохождение", noise: "Шум", result: "Результат", settle: "Закрыть станцию и завершить", retry: "Повторить экспедицию", leave: "Вернуться в центр управления", leaveConfirm: "Экспедиция не завершена безопасно. Выйти?", cancel: "Продолжить экспедицию", confirmLeave: "Выйти", paused: "Экспедиция приостановлена меню настроек", success: "Полевое QSO завершено", failed: "Экспедиция не удалась", siteSelection: "Выбор площадки", setup: "Установка станции", ready: "Готово к вызову", calling: "Вызов CQ", recovering: "Восстановление связи", completed: "Завершено", requiredTopics: "Обязательные темы", expeditionSiteSunward: "Солнечный холм", expeditionSiteCedarBreeze: "Холм Кедровый ветер", expeditionSiteLakeview: "Озёрный холм", failureInvalidWiring: "Ошибка антенны затратила время и батарею", failureInvalidAntenna: "Неверная антенна затратила время и батарею", failureInvalidPower: "Ошибка питания затратила время и батарею", failureWeakLink: "Слабой связи нужен AGN или QRS", failureExchange: "Обмен не принят", failureRetries: "Лимит повторов исчерпан", failureTimeout: "Время истекло", failurePower: "Батарея разряжена", failureSetup: "Попытки настройки исчерпаны", failureCorrupt: "Данные экспедиции не удалось проверить" },
};

const FAILURE_KEYS = Object.freeze({
  INVALID_WIRING: "failureInvalidWiring", INVALID_ANTENNA: "failureInvalidAntenna",
  INVALID_POWER: "failureInvalidPower", WEAK_LINK_REQUIRES_RECOVERY: "failureWeakLink",
  EXCHANGE_RETRIES_EXHAUSTED: "failureRetries", TIMED_OUT: "failureTimeout",
  POWER_DEPLETED: "failurePower", SETUP_RETRIES_EXHAUSTED: "failureSetup",
  CORRUPT_RUN: "failureCorrupt",
});

export function expeditionLeaveRisk(run) {
  if (!run || typeof run !== "object") return "none";
  if (run.status === "completed" && run.settlementStatus !== "settled") return "unsaved";
  if (!["completed", "failed", "abandoned"].includes(run.status)) return "active";
  return "none";
}

export function expeditionUiModel(run, { language = "en", paused = false, ownedLoadoutAvailable = false } = {}) {
  const t = EXPEDITION_TEXT[language] ?? EXPEDITION_TEXT.en;
  const capacity = Number(run?.power?.capacityWh) || 0;
  const remaining = Number(run?.power?.remainingWh) || 0;
  const phase = String(run?.status ?? "site-selection");
  const terminal = ["completed", "failed", "abandoned"].includes(phase);
  const failureReason = String(run?.failureReason ?? "");
  return Object.freeze({
    phase,
    phaseLabel: t[phase === "site-selection" ? "siteSelection" : phase] ?? phase,
    paused: Boolean(paused),
    onAir: ["calling", "exchange", "recovering"].includes(phase),
    portraitVisible: false,
    canSelectSite: phase === "site-selection",
    canSetup: phase === "setup",
    canCallCq: phase === "ready",
    canReceiveReply: phase === "calling",
    canSendExchange: phase === "exchange",
    canRequestAgn: phase === "recovering",
    canRequestQrs: phase === "recovering",
    canRetry: ["failed", "abandoned"].includes(phase),
    canSettle: phase === "completed" && run?.settlementStatus !== "settled",
    loadoutSource: run?.loadout?.source === "owned" ? "owned" : "loan",
    ownedLoadoutAvailable: Boolean(ownedLoadoutAvailable),
    setupMistakes: Number(run?.setupMistakes) || 0,
    battery: Object.freeze({
      remainingWh: Number(remaining.toFixed(2)),
      capacityWh: Number(capacity.toFixed(2)),
      percent: capacity > 0 ? Math.max(0, Math.min(100, Math.round((remaining / capacity) * 100))) : 0,
    }),
    propagation: run?.propagationSnapshot ? Object.freeze({
      level: Number(run.propagationSnapshot.level), noise: Number(run.propagationSnapshot.noise),
    }) : null,
    requiredTopics: Object.freeze(["QTH", "POWER", "ANTENNA"]),
    exchangeHint: run?.fieldSite && run?.loadout
      ? `QTH ${run.fieldSite.qthCode} PWR ${run.loadout.outputPowerWatts}W ANT ${run.loadout.antennaCode}` : "",
    failureKey: failureReason ? FAILURE_KEYS[failureReason] ?? "failureExchange" : null,
    failureText: failureReason ? t[FAILURE_KEYS[failureReason] ?? "failureExchange"] : "",
    result: run?.result?.outcome ?? (terminal ? phase : null),
    leaveRisk: expeditionLeaveRisk(run),
  });
}
