const en = Object.freeze({
  kicker: "THE FIRST OPEN PAGE · CHAPTER 15", title: "Write the First Page", intro: "One ordinary contact made after accepting this chapter is waiting in the log. Keep its facts fixed and choose what the open station should pursue next.",
  contact: "Linked ordinary QSO", callsign: "Callsign", region: "Region", completed: "Completed", reward: "QSO reward", choose: "Choose a fixed station goal", seal: "Seal first page", close: "Close",
  "world-log": "Build a wider world log", "people-network": "Strengthen the people network", "field-operations": "Practice field operations", "public-service": "Support fictional public-service nets", "contest-craft": "Sharpen contest craft",
});
const merge = (values) => Object.freeze({ ...en, ...values });

export const FIRST_PAGE_TEXT = Object.freeze({
  "zh-CN": merge({ kicker: "开放日志的第一页 · 第15章", title: "写下第一页", intro: "接受本章后完成的一次普通联络正在日志中等待。保留真实事实，并选择开放电台接下来要追求的方向。", contact: "关联普通QSO", callsign: "呼号", region: "地区", completed: "完成时间", reward: "QSO奖励", choose: "选择固定电台目标", seal: "封存第一页", close: "关闭", "world-log": "扩展世界日志", "people-network": "巩固人物网络", "field-operations": "练习野外操作", "public-service": "支援虚构公共服务网", "contest-craft": "磨练竞赛技艺" }),
  "zh-TW": merge({ kicker: "開放日誌的第一頁 · 第15章", title: "寫下第一頁", intro: "接受本章後完成的一次普通聯絡正在日誌中等待。保留真實事實，並選擇開放電臺接下來要追求的方向。", contact: "關聯普通QSO", callsign: "呼號", region: "地區", completed: "完成時間", reward: "QSO獎勵", choose: "選擇固定電臺目標", seal: "封存第一頁", close: "關閉", "world-log": "擴展世界日誌", "people-network": "鞏固人物網絡", "field-operations": "練習野外操作", "public-service": "支援虛構公共服務網", "contest-craft": "磨練競賽技藝" }),
  ja: merge({ kicker: "オープンログの最初のページ · 第15章", title: "最初のページを書く", intro: "この章を受けてから完了した通常QSOがログにあります。事実を固定したまま、オープン局の次の目標を選びます。", contact: "紐づく通常QSO", callsign: "コールサイン", region: "地域", completed: "完了時刻", reward: "QSO報酬", choose: "固定局目標を選択", seal: "最初のページを封印", close: "閉じる", "world-log": "世界ログを広げる", "people-network": "人のネットワークを強める", "field-operations": "移動運用を練習する", "public-service": "架空の公共サービス網を支える", "contest-craft": "コンテスト技術を磨く" }),
  en,
  es: merge({ kicker: "LA PRIMERA PÁGINA ABIERTA · CAPÍTULO 15", title: "Escribe la primera página", intro: "Un QSO ordinario completado tras aceptar este capítulo espera en el registro. Conserva sus hechos y elige el próximo objetivo de la estación abierta.", contact: "QSO ordinario vinculado", callsign: "Indicativo", region: "Región", completed: "Completado", reward: "Recompensa QSO", choose: "Elige un objetivo fijo", seal: "Sellar la primera página", close: "Cerrar", "world-log": "Ampliar el registro mundial", "people-network": "Fortalecer la red de personas", "field-operations": "Practicar operaciones de campo", "public-service": "Apoyar redes ficticias de servicio público", "contest-craft": "Mejorar la técnica de concurso" }),
  de: merge({ kicker: "DIE ERSTE OFFENE SEITE · KAPITEL 15", title: "Die erste Seite schreiben", intro: "Ein gewöhnliches QSO nach Annahme dieses Kapitels wartet im Log. Bewahre seine Fakten und wähle das nächste Ziel der offenen Station.", contact: "Verknüpftes gewöhnliches QSO", callsign: "Rufzeichen", region: "Region", completed: "Abgeschlossen", reward: "QSO-Belohnung", choose: "Festes Stationsziel wählen", seal: "Erste Seite versiegeln", close: "Schließen", "world-log": "Das Weltlog erweitern", "people-network": "Das Personennetz stärken", "field-operations": "Feldbetrieb üben", "public-service": "Fiktive öffentliche Netze unterstützen", "contest-craft": "Contest-Fertigkeiten schärfen" }),
  ru: merge({ kicker: "ПЕРВАЯ ОТКРЫТАЯ СТРАНИЦА · ГЛАВА 15", title: "Написать первую страницу", intro: "В журнале ждёт обычная связь, завершённая после принятия главы. Сохрани её факты и выбери следующую цель открытой станции.", contact: "Связанная обычная QSO", callsign: "Позывной", region: "Регион", completed: "Завершено", reward: "Награда QSO", choose: "Выбрать фиксированную цель", seal: "Закрепить первую страницу", close: "Закрыть", "world-log": "Расширить мировой журнал", "people-network": "Укрепить сеть людей", "field-operations": "Практиковать полевую работу", "public-service": "Поддерживать вымышленные общественные сети", "contest-craft": "Отточить контест-навыки" }),
});
