export const LIGHTS_TEXT = Object.freeze({
  "zh-CN": Object.freeze({
    title: "空中灯火", kicker: "纪念通联 · SIM5LT", story: "主线", annual: "年度复刻", practice: "练习",
    station: "活动台", operator: "值机员", remaining: "剩余时间", contacts: "通联", regions: "地区", score: "得分", grade: "评级",
    gradeNone: "未达标", gradeBase: "基础", gradeSilver: "银", gradeGold: "金",
    incoming: "正在接收", awaiting: "等待操作", transmit: "发送", clear: "清空", replay: "回放输入", settle: "记录结果", settled: "已记录", back: "返回管理中心",
    caller: "个呼叫台", leaveConfirm: "活动仍在进行，离开将放弃本轮。确定返回吗？",
    phaseChaseCq: "先听完 SORA 操作的 SIM5LT 呼叫。", phaseChaseCall: "呼叫 SIM5LT，并带上你的呼号。", phaseChaseReport: "听取 SORA 发来的 RST 与地区。", phaseChaseReply: "向 SIM5LT 回报 RST 和你的地区代码。", phaseChaseFinal: "听取结束语，随后由你接管活动台。",
    phaseControlCq: "以 SIM5LT 发出 CQ LGT。", phasePileup: "多个电台同时呼叫，请先完整抄收。", phaseSelection: "选择一个完整呼号，或用 ? 补全唯一部分。", phaseCallerReport: "听取已选电台的 RST 与地区。", phasePlayerReport: "以 SIM5LT 回报 RST 和你的地区。", phaseFinal: "听取对方结束语。", phaseComplete: "本轮结束，可以记录成绩。",
    errorWrongCallsign: "呼号不匹配，请重新抄收。", errorWrongRegion: "地区代码错误，只接受 JP / US / CN / GE / CH / FI。", errorInvalidRst: "RST 必须是合法三位报告。", errorMissingEventToken: "活动 CQ 必须包含 LGT。", errorMissingCq: "请先发 CQ。", errorMissingHandoff: "报文末尾需要 K 或 KN。", errorPartialAmbiguous: "这个部分呼号仍对应多个电台，请再多抄一些。", errorCallsignMisidentified: "该呼号不在本轮 pile-up 中。", errorPartialNoMatch: "没有找到对应呼号。", errorUnsafe: "报文语义不完整，未提交本次交换。", errorGeneric: "报文未被接受，请检查呼号、RST 与地区。",
  }),
  "zh-TW": Object.freeze({
    title: "空中燈火", kicker: "紀念通聯 · SIM5LT", story: "主線", annual: "年度復刻", practice: "練習",
    station: "活動臺", operator: "值機員", remaining: "剩餘時間", contacts: "通聯", regions: "地區", score: "得分", grade: "評級",
    gradeNone: "未達標", gradeBase: "基礎", gradeSilver: "銀", gradeGold: "金",
    incoming: "正在接收", awaiting: "等待操作", transmit: "發送", clear: "清除", replay: "重播輸入", settle: "記錄結果", settled: "已記錄", back: "返回管理中心",
    caller: "個呼叫臺", leaveConfirm: "活動仍在進行，離開將放棄本輪。確定返回嗎？",
    phaseChaseCq: "先聽完 SORA 操作的 SIM5LT 呼叫。", phaseChaseCall: "呼叫 SIM5LT，並帶上你的呼號。", phaseChaseReport: "聽取 SORA 發來的 RST 與地區。", phaseChaseReply: "向 SIM5LT 回報 RST 和你的地區代碼。", phaseChaseFinal: "聽取結束語，隨後由你接管活動臺。",
    phaseControlCq: "以 SIM5LT 發出 CQ LGT。", phasePileup: "多個電臺同時呼叫，請先完整抄收。", phaseSelection: "選擇一個完整呼號，或用 ? 補全唯一部分。", phaseCallerReport: "聽取已選電臺的 RST 與地區。", phasePlayerReport: "以 SIM5LT 回報 RST 和你的地區。", phaseFinal: "聽取對方結束語。", phaseComplete: "本輪結束，可以記錄成績。",
    errorWrongCallsign: "呼號不符，請重新抄收。", errorWrongRegion: "地區代碼錯誤，只接受 JP / US / CN / GE / CH / FI。", errorInvalidRst: "RST 必須是合法三位報告。", errorMissingEventToken: "活動 CQ 必須包含 LGT。", errorMissingCq: "請先發 CQ。", errorMissingHandoff: "報文末尾需要 K 或 KN。", errorPartialAmbiguous: "這個部分呼號仍對應多個電臺，請再多抄一些。", errorCallsignMisidentified: "該呼號不在本輪 pile-up 中。", errorPartialNoMatch: "找不到對應呼號。", errorUnsafe: "報文語意不完整，未提交本次交換。", errorGeneric: "報文未被接受，請檢查呼號、RST 與地區。",
  }),
  ja: Object.freeze({
    title: "空をつなぐ灯", kicker: "記念交信 · SIM5LT", story: "ストーリー", annual: "年次再演", practice: "練習",
    station: "記念局", operator: "運用者", remaining: "残り時間", contacts: "交信", regions: "地域", score: "得点", grade: "評価",
    gradeNone: "未達", gradeBase: "基礎", gradeSilver: "銀", gradeGold: "金",
    incoming: "受信中", awaiting: "操作待ち", transmit: "送信", clear: "消去", replay: "入力再生", settle: "結果を記録", settled: "記録済み", back: "管理センターへ",
    caller: "局が呼出中", leaveConfirm: "イベント進行中です。退出すると今回の運用を破棄します。戻りますか？",
    phaseChaseCq: "SORA が運用する SIM5LT の呼出を最後まで聞きます。", phaseChaseCall: "自局コールを添えて SIM5LT を呼びます。", phaseChaseReport: "SORA からの RST と地域を受信します。", phaseChaseReply: "SIM5LT に RST と自局地域コードを返します。", phaseChaseFinal: "終了を聞いた後、記念局を引き継ぎます。",
    phaseControlCq: "SIM5LT として CQ LGT を送信します。", phasePileup: "複数局が同時に呼んでいます。まず全体を聞いてください。", phaseSelection: "1局の完全なコール、または一意になる部分コールを指定します。", phaseCallerReport: "選んだ局の RST と地域を受信します。", phasePlayerReport: "SIM5LT として RST と自局地域を返します。", phaseFinal: "相手局の終了を受信します。", phaseComplete: "運用終了。結果を記録できます。",
    errorWrongCallsign: "コールが一致しません。もう一度受信してください。", errorWrongRegion: "地域コードは JP / US / CN / GE / CH / FI のみです。", errorInvalidRst: "RST は正しい3桁で送ってください。", errorMissingEventToken: "イベント CQ には LGT が必要です。", errorMissingCq: "先に CQ を送ってください。", errorMissingHandoff: "末尾に K または KN が必要です。", errorPartialAmbiguous: "部分コールが複数局に一致します。もう少し受信してください。", errorCallsignMisidentified: "その局は今回の pile-up にいません。", errorPartialNoMatch: "一致する局がありません。", errorUnsafe: "意味が不完全なため交換を確定しませんでした。", errorGeneric: "受理できません。コール、RST、地域を確認してください。",
  }),
  en: Object.freeze({
    title: "Lights Across the Air", kicker: "Memorial operation · SIM5LT", story: "Story", annual: "Annual replay", practice: "Practice",
    station: "Event station", operator: "Operator", remaining: "Time left", contacts: "QSOs", regions: "Regions", score: "Score", grade: "Grade",
    gradeNone: "Not qualified", gradeBase: "Base", gradeSilver: "Silver", gradeGold: "Gold",
    incoming: "Receiving", awaiting: "Awaiting operator", transmit: "Transmit", clear: "Clear", replay: "Replay input", settle: "Record result", settled: "Recorded", back: "Management Center",
    caller: "calling stations", leaveConfirm: "The event is still active. Leaving will discard this run. Return anyway?",
    phaseChaseCq: "Listen to SORA operating SIM5LT before answering.", phaseChaseCall: "Call SIM5LT with your own callsign.", phaseChaseReport: "Copy SORA's RST and region.", phaseChaseReply: "Return an RST and your region code to SIM5LT.", phaseChaseFinal: "Copy the signoff; you will take over the event station next.",
    phaseControlCq: "Call CQ LGT as SIM5LT.", phasePileup: "Several stations are calling together. Copy the pile-up first.", phaseSelection: "Select one full callsign, or use ? for a unique partial.", phaseCallerReport: "Copy the selected station's RST and region.", phasePlayerReport: "Return an RST and your region as SIM5LT.", phaseFinal: "Copy the other station's signoff.", phaseComplete: "The run is complete and ready to record.",
    errorWrongCallsign: "Callsign mismatch. Copy the station again.", errorWrongRegion: "Wrong region; use JP / US / CN / GE / CH / FI.", errorInvalidRst: "RST must be a valid three-digit report.", errorMissingEventToken: "An event CQ must include LGT.", errorMissingCq: "Send CQ first.", errorMissingHandoff: "End the message with K or KN.", errorPartialAmbiguous: "That partial still matches several stations; copy more characters.", errorCallsignMisidentified: "That callsign is not in this pile-up.", errorPartialNoMatch: "No station matches that call.", errorUnsafe: "Meaning was incomplete, so the exchange was not committed.", errorGeneric: "Message not accepted. Check callsigns, RST, and region.",
  }),
  es: Object.freeze({
    title: "Luces en el aire", kicker: "Operación conmemorativa · SIM5LT", story: "Historia", annual: "Repetición anual", practice: "Práctica",
    station: "Estación especial", operator: "Operador", remaining: "Tiempo restante", contacts: "QSO", regions: "Regiones", score: "Puntos", grade: "Nivel",
    gradeNone: "Sin nivel", gradeBase: "Base", gradeSilver: "Plata", gradeGold: "Oro",
    incoming: "Recibiendo", awaiting: "Esperando al operador", transmit: "Transmitir", clear: "Borrar", replay: "Repetir entrada", settle: "Registrar resultado", settled: "Registrado", back: "Centro de Gestión",
    caller: "estaciones llamando", leaveConfirm: "El evento sigue activo. Salir descartará esta ronda. ¿Volver igualmente?",
    phaseChaseCq: "Escucha a SORA operar SIM5LT antes de responder.", phaseChaseCall: "Llama a SIM5LT con tu indicativo.", phaseChaseReport: "Copia el RST y la región de SORA.", phaseChaseReply: "Devuelve RST y tu código regional a SIM5LT.", phaseChaseFinal: "Copia la despedida; después tomarás la estación.",
    phaseControlCq: "Llama CQ LGT como SIM5LT.", phasePileup: "Varias estaciones llaman a la vez; copia primero el pile-up.", phaseSelection: "Elige un indicativo completo o una parte única con ?.", phaseCallerReport: "Copia el RST y región de la estación elegida.", phasePlayerReport: "Devuelve RST y tu región como SIM5LT.", phaseFinal: "Copia la despedida de la otra estación.", phaseComplete: "La ronda terminó y puede registrarse.",
    errorWrongCallsign: "El indicativo no coincide; vuelve a copiarlo.", errorWrongRegion: "Región incorrecta; usa JP / US / CN / GE / CH / FI.", errorInvalidRst: "El RST debe tener tres cifras válidas.", errorMissingEventToken: "El CQ del evento debe incluir LGT.", errorMissingCq: "Envía primero CQ.", errorMissingHandoff: "Termina con K o KN.", errorPartialAmbiguous: "La parte coincide con varias estaciones; copia más caracteres.", errorCallsignMisidentified: "Ese indicativo no está en este pile-up.", errorPartialNoMatch: "Ninguna estación coincide.", errorUnsafe: "El significado estaba incompleto y no se confirmó el intercambio.", errorGeneric: "Mensaje no aceptado. Revisa indicativos, RST y región.",
  }),
  de: Object.freeze({
    title: "Lichter über Funk", kicker: "Gedenkbetrieb · SIM5LT", story: "Geschichte", annual: "Jährliche Wiederholung", practice: "Übung",
    station: "Sonderstation", operator: "Operator", remaining: "Restzeit", contacts: "QSOs", regions: "Regionen", score: "Punkte", grade: "Stufe",
    gradeNone: "Nicht erreicht", gradeBase: "Basis", gradeSilver: "Silber", gradeGold: "Gold",
    incoming: "Empfang", awaiting: "Warte auf Operator", transmit: "Senden", clear: "Löschen", replay: "Eingabe abspielen", settle: "Ergebnis speichern", settled: "Gespeichert", back: "Verwaltungszentrum",
    caller: "rufende Stationen", leaveConfirm: "Der Eventbetrieb läuft. Beim Verlassen wird dieser Durchgang verworfen. Trotzdem zurück?",
    phaseChaseCq: "Höre SORA beim Betrieb von SIM5LT zu, bevor du antwortest.", phaseChaseCall: "Rufe SIM5LT mit deinem eigenen Rufzeichen.", phaseChaseReport: "Nimm RST und Region von SORA auf.", phaseChaseReply: "Gib SIM5LT RST und deinen Regionscode zurück.", phaseChaseFinal: "Nimm den Abschluss auf; danach übernimmst du die Sonderstation.",
    phaseControlCq: "Rufe als SIM5LT CQ LGT.", phasePileup: "Mehrere Stationen rufen gleichzeitig. Höre zuerst den Pile-up.", phaseSelection: "Wähle ein volles Rufzeichen oder einen eindeutigen Teil mit ?.", phaseCallerReport: "Nimm RST und Region der gewählten Station auf.", phasePlayerReport: "Gib als SIM5LT RST und deine Region zurück.", phaseFinal: "Nimm den Abschluss der Gegenstation auf.", phaseComplete: "Der Durchgang ist beendet und kann gespeichert werden.",
    errorWrongCallsign: "Rufzeichen stimmt nicht. Bitte erneut aufnehmen.", errorWrongRegion: "Falsche Region; nutze JP / US / CN / GE / CH / FI.", errorInvalidRst: "RST muss ein gültiger dreistelliger Rapport sein.", errorMissingEventToken: "Ein Event-CQ muss LGT enthalten.", errorMissingCq: "Sende zuerst CQ.", errorMissingHandoff: "Nachricht mit K oder KN beenden.", errorPartialAmbiguous: "Der Teil passt zu mehreren Stationen; nimm mehr Zeichen auf.", errorCallsignMisidentified: "Dieses Rufzeichen ist nicht im Pile-up.", errorPartialNoMatch: "Keine passende Station gefunden.", errorUnsafe: "Die Bedeutung war unvollständig; der Austausch wurde nicht bestätigt.", errorGeneric: "Nachricht nicht akzeptiert. Prüfe Rufzeichen, RST und Region.",
  }),
  ru: Object.freeze({
    title: "Огни в эфире", kicker: "Памятная работа · SIM5LT", story: "Сюжет", annual: "Ежегодный повтор", practice: "Практика",
    station: "Спецстанция", operator: "Оператор", remaining: "Осталось", contacts: "QSO", regions: "Регионы", score: "Очки", grade: "Уровень",
    gradeNone: "Не выполнено", gradeBase: "Базовый", gradeSilver: "Серебро", gradeGold: "Золото",
    incoming: "Приём", awaiting: "Ожидание оператора", transmit: "Передать", clear: "Очистить", replay: "Повторить ввод", settle: "Записать результат", settled: "Записано", back: "Центр управления",
    caller: "вызывающих станций", leaveConfirm: "Событие ещё идёт. Выход отменит эту попытку. Всё равно вернуться?",
    phaseChaseCq: "Прослушайте, как SORA работает позывным SIM5LT.", phaseChaseCall: "Вызовите SIM5LT со своим позывным.", phaseChaseReport: "Примите RST и регион от SORA.", phaseChaseReply: "Передайте SIM5LT RST и код своего региона.", phaseChaseFinal: "Примите завершение, затем вы возьмёте спецстанцию.",
    phaseControlCq: "Передайте CQ LGT позывным SIM5LT.", phasePileup: "Несколько станций вызывают одновременно. Сначала примите pile-up.", phaseSelection: "Выберите полный позывной или уникальную часть с ?.", phaseCallerReport: "Примите RST и регион выбранной станции.", phasePlayerReport: "Передайте RST и свой регион позывным SIM5LT.", phaseFinal: "Примите завершение другой станции.", phaseComplete: "Попытка завершена и готова к записи.",
    errorWrongCallsign: "Позывной не совпал. Примите его снова.", errorWrongRegion: "Неверный регион; используйте JP / US / CN / GE / CH / FI.", errorInvalidRst: "RST должен быть допустимым трёхзначным рапортом.", errorMissingEventToken: "В CQ события должен быть LGT.", errorMissingCq: "Сначала передайте CQ.", errorMissingHandoff: "Завершите сообщение K или KN.", errorPartialAmbiguous: "Часть совпадает с несколькими станциями; примите больше знаков.", errorCallsignMisidentified: "Этого позывного нет в pile-up.", errorPartialNoMatch: "Совпадающая станция не найдена.", errorUnsafe: "Смысл неполон, обмен не подтверждён.", errorGeneric: "Сообщение не принято. Проверьте позывные, RST и регион.",
  }),
});

export function lightsText(language) {
  return LIGHTS_TEXT[language] ?? LIGHTS_TEXT.en;
}
