const en = Object.freeze({
  kicker: "POST-STORY · OFFLINE", title: "Open Station", intro: "The story is complete. These five lines are projected only from this save's durable records; there is no network or leaderboard.", close: "Close", firstGoal: "First-page goal", activeGoal: "Active annual goal", changeGoal: "Change fixed goal", recent: "Recent ordinary contacts", none: "No retained ordinary contacts", updated: "Goal updated",
  "world-log": "World log", "award-wall": "Award wall", "people-network": "People network", "station-engineering": "Station engineering", "annual-career": "Annual career", "field-operations": "Field operations", "public-service": "Public-service practice", "contest-craft": "Contest craft",
  ordinaryQsos: "Ordinary QSOs", regions: "Regions", people: "People", propagationConditions: "Propagation conditions", prefixes: "Prefixes", achievements: "Achievements", storyCertificates: "Story certificates", relationships: "Relationships", qslRecords: "QSL records", technologies: "Technologies", ownedItems: "Owned items", lightsYears: "Lights years", expeditions: "Expeditions", contestBest: "Contest best",
});
const merged = (values) => Object.freeze({ ...en, ...values });

export const OPEN_STATION_TEXT = Object.freeze({
  "zh-CN": merged({ kicker: "故事之后 · 离线", title: "开放电台", intro: "故事已经完成。五条进度只来自本存档的持久记录，不含联网或排行榜。", close: "关闭", firstGoal: "第一页目标", activeGoal: "当前年度目标", changeGoal: "切换固定目标", recent: "最近普通联络", none: "没有保留的普通联络", updated: "目标已更新", "world-log": "世界日志", "award-wall": "荣誉墙", "people-network": "人物网络", "station-engineering": "台站工程", "annual-career": "年度生涯", "field-operations": "野外操作", "public-service": "公共服务练习", "contest-craft": "竞赛技艺", ordinaryQsos: "普通QSO", regions: "地区", people: "人物", propagationConditions: "传播条件", prefixes: "前缀", achievements: "成就", storyCertificates: "故事证书", relationships: "关系", qslRecords: "QSL记录", technologies: "技术", ownedItems: "拥有物品", lightsYears: "灯火年份", expeditions: "远征", contestBest: "竞赛最佳" }),
  "zh-TW": merged({ kicker: "故事之後 · 離線", title: "開放電臺", intro: "故事已經完成。五條進度只來自本存檔的持久記錄，不含連線或排行榜。", close: "關閉", firstGoal: "第一頁目標", activeGoal: "目前年度目標", changeGoal: "切換固定目標", recent: "最近普通聯絡", none: "沒有保留的普通聯絡", updated: "目標已更新", "world-log": "世界日誌", "award-wall": "榮譽牆", "people-network": "人物網絡", "station-engineering": "臺站工程", "annual-career": "年度生涯", "field-operations": "野外操作", "public-service": "公共服務練習", "contest-craft": "競賽技藝", ordinaryQsos: "普通QSO", regions: "地區", people: "人物", propagationConditions: "傳播條件", prefixes: "前綴", achievements: "成就", storyCertificates: "故事證書", relationships: "關係", qslRecords: "QSL記錄", technologies: "技術", ownedItems: "擁有物品", lightsYears: "燈火年份", expeditions: "遠征", contestBest: "競賽最佳" }),
  ja: merged({ kicker: "物語の後 · オフライン", title: "オープンステーション", intro: "物語は完了しました。五つの進捗は保存済み記録だけから作られ、通信やランキングはありません。", close: "閉じる", firstGoal: "最初の目標", activeGoal: "現在の年間目標", changeGoal: "固定目標を変更", recent: "最近の通常QSO", none: "通常QSOはありません", updated: "目標を更新しました", "world-log": "世界ログ", "award-wall": "アワード壁", "people-network": "人物ネットワーク", "station-engineering": "局設備", "annual-career": "年間キャリア", "field-operations": "移動運用", "public-service": "公共サービス練習", "contest-craft": "コンテスト技術", ordinaryQsos: "通常QSO", regions: "地域", people: "人物", propagationConditions: "伝搬条件", prefixes: "プリフィックス", achievements: "実績", storyCertificates: "物語証明", relationships: "関係", qslRecords: "QSL記録", technologies: "技術", ownedItems: "所有品", lightsYears: "灯火年", expeditions: "遠征", contestBest: "コンテスト最高" }),
  en,
  es: merged({ kicker: "DESPUÉS DE LA HISTORIA · SIN CONEXIÓN", title: "Estación Abierta", intro: "La historia terminó. Las cinco líneas proceden solo de registros duraderos; no hay red ni clasificación.", close: "Cerrar", firstGoal: "Objetivo inicial", activeGoal: "Objetivo anual activo", changeGoal: "Cambiar objetivo fijo", recent: "Contactos ordinarios recientes", none: "Sin contactos retenidos", updated: "Objetivo actualizado", "world-log": "Registro mundial", "award-wall": "Muro de premios", "people-network": "Red de personas", "station-engineering": "Ingeniería de estación", "annual-career": "Carrera anual", "field-operations": "Operación de campo", "public-service": "Práctica de servicio público", "contest-craft": "Técnica de concurso", ordinaryQsos: "QSO ordinarios", regions: "Regiones", people: "Personas", propagationConditions: "Condiciones", prefixes: "Prefijos", achievements: "Logros", storyCertificates: "Certificados", relationships: "Relaciones", qslRecords: "Registros QSL", technologies: "Tecnologías", ownedItems: "Equipo propio", lightsYears: "Años Lights", expeditions: "Expediciones", contestBest: "Mejor concurso" }),
  de: merged({ kicker: "NACH DER GESCHICHTE · OFFLINE", title: "Open Station", intro: "Die Geschichte ist abgeschlossen. Fünf Zeilen stammen nur aus dauerhaften Daten; ohne Netz oder Rangliste.", close: "Schließen", firstGoal: "Erstes Ziel", activeGoal: "Aktives Jahresziel", changeGoal: "Festes Ziel wechseln", recent: "Letzte normale Kontakte", none: "Keine Kontakte gespeichert", updated: "Ziel aktualisiert", "world-log": "Weltlog", "award-wall": "Auszeichnungswand", "people-network": "Personennetz", "station-engineering": "Stationstechnik", "annual-career": "Jahreslaufbahn", "field-operations": "Feldbetrieb", "public-service": "Öffentlicher Übungsdienst", "contest-craft": "Contest-Fertigkeit", ordinaryQsos: "Normale QSOs", regions: "Regionen", people: "Menschen", propagationConditions: "Ausbreitung", prefixes: "Präfixe", achievements: "Erfolge", storyCertificates: "Story-Zertifikate", relationships: "Beziehungen", qslRecords: "QSL-Daten", technologies: "Technologien", ownedItems: "Eigene Geräte", lightsYears: "Lights-Jahre", expeditions: "Expeditionen", contestBest: "Contest-Bestwert" }),
  ru: merged({ kicker: "ПОСЛЕ ИСТОРИИ · АВТОНОМНО", title: "Открытая станция", intro: "История завершена. Пять линий строятся только по сохранённым данным, без сети и рейтинга.", close: "Закрыть", firstGoal: "Первая цель", activeGoal: "Текущая годовая цель", changeGoal: "Сменить фиксированную цель", recent: "Последние обычные связи", none: "Обычных связей нет", updated: "Цель обновлена", "world-log": "Мировой журнал", "award-wall": "Стена наград", "people-network": "Сеть людей", "station-engineering": "Инженерия станции", "annual-career": "Годовая карьера", "field-operations": "Полевая работа", "public-service": "Учебная общественная служба", "contest-craft": "Контест-навыки", ordinaryQsos: "Обычные QSO", regions: "Регионы", people: "Люди", propagationConditions: "Условия", prefixes: "Префиксы", achievements: "Достижения", storyCertificates: "Сертификаты", relationships: "Связи", qslRecords: "QSL", technologies: "Технологии", ownedItems: "Оборудование", lightsYears: "Годы Lights", expeditions: "Экспедиции", contestBest: "Лучший контест" }),
});
