import { useEffect } from "react";
import { ArrowLeft, CheckCircle, IdentificationCard, Radio, Users, X } from "@phosphor-icons/react";
import { QSL_CHOICES } from "../game/qslRecords.js";

export const QSL_TEXT = {
  "zh-CN": { title: "人物与 QSL", people: "人物关系", cards: "QSL 卡片", empty: "还没有收到 QSL 记录。", qsos: "通联", lastCall: "最近呼号", believe: "相信这段叙述", requestReview: "请求复核", defer: "暂不判断", confirmed: "选择已确认", close: "返回管理中心", "qsl.player.hill-signal": "你从山丘临时台发出了完整的通联交换。", "qsl.operator.sora-hill-reply": "Sora 回忆起山风中的信号，并确认了这次通联。", "qsl.player.lights-contact": "你在灯火纪念台完成了这次通联。", "qsl.operator.lights-reply": "对方确认了灯火纪念台的信号。", "qsl.player.clarification-request": "你依据案件编号请求SORA澄清QSL记录。", "qsl.operator.sora-clarification": "SORA在空中重新核对了山丘通联。" },
  "zh-TW": { title: "人物與 QSL", people: "人物關係", cards: "QSL 卡片", empty: "尚未收到 QSL 記錄。", qsos: "通聯", lastCall: "最近呼號", believe: "相信這段敘述", requestReview: "請求複核", defer: "暫不判斷", confirmed: "選擇已確認", close: "返回管理中心", "qsl.player.hill-signal": "你從山丘臨時臺發出了完整的通聯交換。", "qsl.operator.sora-hill-reply": "Sora 回憶起山風中的訊號，並確認了這次通聯。", "qsl.player.lights-contact": "你在燈火紀念臺完成了這次通聯。", "qsl.operator.lights-reply": "對方確認了燈火紀念臺的訊號。", "qsl.player.clarification-request": "你依據案件編號請求SORA澄清QSL記錄。", "qsl.operator.sora-clarification": "SORA在空中重新核對了山丘通聯。" },
  ja: { title: "人物と QSL", people: "人物関係", cards: "QSL カード", empty: "QSL 記録はまだありません。", qsos: "交信", lastCall: "最近のコール", believe: "この記述を信じる", requestReview: "再確認を依頼", defer: "判断を保留", confirmed: "選択確定済み", close: "管理センターへ", "qsl.player.hill-signal": "丘の移動局から完全な交信情報を送りました。", "qsl.operator.sora-hill-reply": "Sora は山風の中の信号を覚えており、この交信を確認しました。", "qsl.player.lights-contact": "灯火記念局でこの交信を完了しました。", "qsl.operator.lights-reply": "相手局は灯火記念局の信号を確認しました。", "qsl.player.clarification-request": "案件番号を使ってSORAにQSL記録の確認を求めました。", "qsl.operator.sora-clarification": "SORAは無線で丘の交信を再確認しました。" },
  en: { title: "People & QSL", people: "People and relationships", cards: "QSL cards", empty: "No QSL records have arrived yet.", qsos: "QSOs", lastCall: "Last callsign", believe: "Believe this account", requestReview: "Request review", defer: "Defer judgment", confirmed: "Choice confirmed", close: "Return to Management Center", "qsl.player.hill-signal": "You sent a complete exchange from the hilltop field station.", "qsl.operator.sora-hill-reply": "Sora remembers your signal in the mountain wind and confirms the contact.", "qsl.player.lights-contact": "You completed this contact at the Lights memorial station.", "qsl.operator.lights-reply": "The other operator confirms the Lights memorial signal.", "qsl.player.clarification-request": "You asked SORA to clarify the QSL record by case number.", "qsl.operator.sora-clarification": "SORA checked the hilltop contact again over the air." },
  es: { title: "Personas y QSL", people: "Personas y relaciones", cards: "Tarjetas QSL", empty: "Todavía no hay registros QSL.", qsos: "QSO", lastCall: "Último indicativo", believe: "Creer este relato", requestReview: "Pedir revisión", defer: "Aplazar decisión", confirmed: "Elección confirmada", close: "Volver al Centro de Gestión", "qsl.player.hill-signal": "Enviaste un intercambio completo desde la estación portátil de la colina.", "qsl.operator.sora-hill-reply": "Sora recuerda tu señal entre el viento de la montaña y confirma el contacto.", "qsl.player.lights-contact": "Completaste este contacto en la estación conmemorativa Luces.", "qsl.operator.lights-reply": "La otra estación confirma la señal conmemorativa Luces.", "qsl.player.clarification-request": "Pediste a SORA que aclarara la QSL por número de caso.", "qsl.operator.sora-clarification": "SORA volvió a comprobar el contacto de la colina por radio." },
  de: { title: "Personen & QSL", people: "Personen und Beziehungen", cards: "QSL-Karten", empty: "Noch keine QSL-Einträge vorhanden.", qsos: "QSOs", lastCall: "Letztes Rufzeichen", believe: "Dieser Darstellung glauben", requestReview: "Prüfung anfordern", defer: "Urteil vertagen", confirmed: "Auswahl bestätigt", close: "Zur Verwaltungszentrale", "qsl.player.hill-signal": "Du hast einen vollständigen Austausch von der tragbaren Bergstation gesendet.", "qsl.operator.sora-hill-reply": "Sora erinnert sich an dein Signal im Bergwind und bestätigt den Kontakt.", "qsl.player.lights-contact": "Du hast diesen Kontakt an der Lights-Gedenkstation abgeschlossen.", "qsl.operator.lights-reply": "Die Gegenstation bestätigt das Signal der Lights-Gedenkstation.", "qsl.player.clarification-request": "Du hast SORA anhand der Fallnummer um QSL-Klärung gebeten.", "qsl.operator.sora-clarification": "SORA prüfte den Hügelkontakt noch einmal über Funk." },
  ru: { title: "Люди и QSL", people: "Люди и отношения", cards: "Карточки QSL", empty: "Записей QSL пока нет.", qsos: "QSO", lastCall: "Последний позывной", believe: "Поверить рассказу", requestReview: "Запросить проверку", defer: "Отложить решение", confirmed: "Выбор подтверждён", close: "В центр управления", "qsl.player.hill-signal": "Вы передали полный обмен с полевой станции на холме.", "qsl.operator.sora-hill-reply": "Sora помнит ваш сигнал в горном ветре и подтверждает связь.", "qsl.player.lights-contact": "Вы завершили эту связь на памятной станции «Огни».", "qsl.operator.lights-reply": "Другая станция подтверждает сигнал памятной станции «Огни».", "qsl.player.clarification-request": "Вы попросили SORA уточнить QSL по номеру дела.", "qsl.operator.sora-clarification": "SORA ещё раз сверила связь с холма в эфире." },
};

const choiceKey = { believe: "believe", "request-review": "requestReview", defer: "defer" };

export function PeopleAndQslModal({ language, save, onConfirmChoice, onClose }) {
  const t = QSL_TEXT[language] ?? QSL_TEXT.en;
  const records = save.qslRecords ?? [];
  const relationships = save.operatorRelationships ?? [];
  useEffect(() => {
    function onKeyDown(event) {
      if (event.key !== "Escape" || event.repeat) return;
      event.preventDefault();
      onClose();
    }
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [onClose]);
  return <div className="modal-backdrop people-qsl-backdrop"><section className="people-qsl-modal" data-testid="people-qsl-modal" role="dialog" aria-modal="true">
    <header><Users size={32} weight="fill" /><h2>{t.title}</h2><button className="icon-button" onClick={onClose} aria-label={t.close}><X size={22} /></button></header>
    <div className="people-qsl-columns">
      <section><h3><IdentificationCard />{t.people}</h3><div className="people-list">{relationships.map((relationship) => <article key={relationship.personId}><Radio /><strong>{relationship.lastCallsign ?? relationship.callsign ?? relationship.personId}</strong><small>{t.qsos}: {relationship.completedQsos ?? 0}</small><code>{relationship.personId}</code></article>)}</div></section>
      <section><h3><Radio />{t.cards}</h3>{records.length === 0 ? <p>{t.empty}</p> : <div className="qsl-card-list">{records.map((record) => <article key={record.id} data-qsl-id={record.id}><header><strong>{record.callsign}</strong><code>{record.personId}</code></header><p data-narrative-key={record.playerNarrativeKey}>{t[record.playerNarrativeKey]}</p><p data-narrative-key={record.operatorNarrativeKey}>{t[record.operatorNarrativeKey]}</p><small>{new Date(record.createdAt).toLocaleString(language)}</small>{record.choice ? <><b><CheckCircle />{t.confirmed}: {t[choiceKey[record.choice]]}</b>{window.cwgameSystem?.qaCapture && <button hidden data-action="qa-confirm-qsl-duplicate" onClick={() => onConfirmChoice(record.id, record.choice)}>QA duplicate confirmation</button>}</> : <div>{QSL_CHOICES.map((choice) => <button key={choice} data-qsl-choice={choice} onClick={() => onConfirmChoice(record.id, choice)}>{t[choiceKey[choice]]}</button>)}</div>}</article>)}</div>}</section>
    </div>
    <footer><button onClick={onClose}><ArrowLeft />{t.close}</button></footer>
  </section></div>;
}
