import { QSL_STORY_PHASES } from "../game/qslStoryRun.js";

export const QSL_STORY_TEXT = Object.freeze({
  "zh-CN": Object.freeze({ title: "QSL 疑云", kicker: "第 07 章", playerAccount: "你的记录", operatorAccount: "SORA 的记录", initialStance: "最初判断", reviewAccounts: "比对双方记录", sourceRequired: "请先在“人物与 QSL”中确认山丘通联卡片。", clarification: "澄清电文", clarificationHint: "发送 QSL {CASE} DE {CALL} PSE K", send: "发送澄清请求", receive: "抄收 SORA 回应", soraReply: "SORA 确认了山丘通联，并请你给出最终判断。", choose: "最终判断", believe: "相信叙述", requestReview: "请求进一步复核", defer: "暂不判断", settle: "记录并结案", success: "QSL 案件已结案", failed: "澄清失败", retry: "重新调查", agn: "AGN K 重发", qrs: "QRS K 慢发", leave: "返回管理中心", leaveConfirm: "本次QSL调查尚未安全结案，确认离开？", cancel: "继续调查", confirmLeave: "确认离开", paused: "设置菜单已暂停QSL调查", case: "案件", errors: "错误", FORMAT_INVALID: "电文格式不正确", CASE_MISMATCH: "QSL案件编号不匹配", CALLSIGN_MISMATCH: "本台呼号不匹配", QSL_REQUIRED: "电文必须以QSL开头", SEMANTIC_UNSAFE: "语义安全检查未通过" }),
  "zh-TW": Object.freeze({ title: "QSL 疑雲", kicker: "第 07 章", playerAccount: "你的記錄", operatorAccount: "SORA 的記錄", initialStance: "最初判斷", reviewAccounts: "比對雙方記錄", sourceRequired: "請先在「人物與 QSL」中確認山丘通聯卡片。", clarification: "澄清電文", clarificationHint: "發送 QSL {CASE} DE {CALL} PSE K", send: "發送澄清請求", receive: "抄收 SORA 回應", soraReply: "SORA 確認了山丘通聯，並請你給出最終判斷。", choose: "最終判斷", believe: "相信敘述", requestReview: "請求進一步複核", defer: "暫不判斷", settle: "記錄並結案", success: "QSL 案件已結案", failed: "澄清失敗", retry: "重新調查", agn: "AGN K 重發", qrs: "QRS K 慢發", leave: "返回管理中心", leaveConfirm: "本次QSL調查尚未安全結案，確認離開？", cancel: "繼續調查", confirmLeave: "確認離開", paused: "設定選單已暫停QSL調查", case: "案件", errors: "錯誤", FORMAT_INVALID: "電文格式不正確", CASE_MISMATCH: "QSL案件編號不符", CALLSIGN_MISMATCH: "本臺呼號不符", QSL_REQUIRED: "電文必須以QSL開頭", SEMANTIC_UNSAFE: "語意安全檢查未通過" }),
  ja: Object.freeze({ title: "QSL の疑問", kicker: "第 07 章", playerAccount: "あなたの記録", operatorAccount: "SORA の記録", initialStance: "最初の判断", reviewAccounts: "双方の記録を照合", sourceRequired: "先に「人物とQSL」で丘のQSLカードを確認してください。", clarification: "確認電文", clarificationHint: "QSL {CASE} DE {CALL} PSE K を送信", send: "確認を送信", receive: "SORA の応答を受信", soraReply: "SORA は丘での交信を確認し、最終判断を求めています。", choose: "最終判断", believe: "記述を信じる", requestReview: "追加確認を依頼", defer: "判断を保留", settle: "記録して完了", success: "QSL案件を完了しました", failed: "確認に失敗", retry: "再調査", agn: "AGN K で再送", qrs: "QRS K で低速", leave: "管理センターへ", leaveConfirm: "QSL調査は未完了です。退出しますか？", cancel: "調査を続ける", confirmLeave: "退出する", paused: "設定メニューでQSL調査を一時停止中", case: "案件", errors: "エラー", FORMAT_INVALID: "電文形式が正しくありません", CASE_MISMATCH: "QSL案件番号が一致しません", CALLSIGN_MISMATCH: "自局コールが一致しません", QSL_REQUIRED: "電文はQSLで始めてください", SEMANTIC_UNSAFE: "意味安全チェックに失敗しました" }),
  en: Object.freeze({ title: "The QSL Question", kicker: "Chapter 07", playerAccount: "Your account", operatorAccount: "SORA's account", initialStance: "Initial stance", reviewAccounts: "Compare both accounts", sourceRequired: "Confirm the hilltop QSL in People & QSL first.", clarification: "Clarification traffic", clarificationHint: "Send QSL {CASE} DE {CALL} PSE K", send: "Send clarification request", receive: "Copy SORA's reply", soraReply: "SORA confirms the hilltop contact and asks for your final judgment.", choose: "Final judgment", believe: "Believe the account", requestReview: "Request further review", defer: "Defer judgment", settle: "Record and close case", success: "QSL case closed", failed: "Clarification failed", retry: "Retry investigation", agn: "Repeat — AGN K", qrs: "Slower — QRS K", leave: "Return to Management Center", leaveConfirm: "This QSL investigation is not safely closed. Leave anyway?", cancel: "Continue investigation", confirmLeave: "Leave investigation", paused: "QSL investigation paused by settings", case: "Case", errors: "Errors", FORMAT_INVALID: "Message format is invalid", CASE_MISMATCH: "QSL case number does not match", CALLSIGN_MISMATCH: "Your callsign does not match", QSL_REQUIRED: "Message must begin with QSL", SEMANTIC_UNSAFE: "Semantic safety check failed" }),
  es: Object.freeze({ title: "La duda QSL", kicker: "Capítulo 07", playerAccount: "Tu relato", operatorAccount: "Relato de SORA", initialStance: "Postura inicial", reviewAccounts: "Comparar ambos relatos", sourceRequired: "Confirma primero la QSL de la colina en Personas y QSL.", clarification: "Mensaje de aclaración", clarificationHint: "Envía QSL {CASE} DE {CALL} PSE K", send: "Enviar aclaración", receive: "Copiar respuesta de SORA", soraReply: "SORA confirma el contacto de la colina y pide tu decisión final.", choose: "Decisión final", believe: "Creer el relato", requestReview: "Pedir otra revisión", defer: "Aplazar decisión", settle: "Registrar y cerrar", success: "Caso QSL cerrado", failed: "Aclaración fallida", retry: "Reintentar investigación", agn: "Repetir — AGN K", qrs: "Más lento — QRS K", leave: "Volver al Centro de Gestión", leaveConfirm: "La investigación QSL no está cerrada. ¿Salir?", cancel: "Continuar", confirmLeave: "Salir", paused: "Investigación QSL pausada por ajustes", case: "Caso", errors: "Errores", FORMAT_INVALID: "Formato de mensaje no válido", CASE_MISMATCH: "El número de caso no coincide", CALLSIGN_MISMATCH: "Tu indicativo no coincide", QSL_REQUIRED: "El mensaje debe empezar por QSL", SEMANTIC_UNSAFE: "Falló la comprobación semántica" }),
  de: Object.freeze({ title: "Die QSL-Frage", kicker: "Kapitel 07", playerAccount: "Dein Bericht", operatorAccount: "SORAs Bericht", initialStance: "Erstes Urteil", reviewAccounts: "Beide Berichte vergleichen", sourceRequired: "Bestätige zuerst die Hügel-QSL unter Personen & QSL.", clarification: "Klärungsnachricht", clarificationHint: "QSL {CASE} DE {CALL} PSE K senden", send: "Klärung senden", receive: "SORAs Antwort aufnehmen", soraReply: "SORA bestätigt den Hügelkontakt und bittet um dein endgültiges Urteil.", choose: "Endgültiges Urteil", believe: "Bericht glauben", requestReview: "Weitere Prüfung anfordern", defer: "Urteil vertagen", settle: "Speichern und abschließen", success: "QSL-Fall abgeschlossen", failed: "Klärung fehlgeschlagen", retry: "Erneut untersuchen", agn: "Wiederholen — AGN K", qrs: "Langsamer — QRS K", leave: "Zur Verwaltungszentrale", leaveConfirm: "Die QSL-Untersuchung ist nicht abgeschlossen. Verlassen?", cancel: "Fortsetzen", confirmLeave: "Verlassen", paused: "QSL-Untersuchung durch Einstellungen pausiert", case: "Fall", errors: "Fehler", FORMAT_INVALID: "Nachrichtenformat ist ungültig", CASE_MISMATCH: "QSL-Fallnummer stimmt nicht", CALLSIGN_MISMATCH: "Dein Rufzeichen stimmt nicht", QSL_REQUIRED: "Nachricht muss mit QSL beginnen", SEMANTIC_UNSAFE: "Semantische Sicherheitsprüfung fehlgeschlagen" }),
  ru: Object.freeze({ title: "Вопрос QSL", kicker: "Глава 07", playerAccount: "Ваша запись", operatorAccount: "Запись SORA", initialStance: "Первое решение", reviewAccounts: "Сравнить обе записи", sourceRequired: "Сначала подтвердите QSL с холма в разделе «Люди и QSL».", clarification: "Уточняющее сообщение", clarificationHint: "Передайте QSL {CASE} DE {CALL} PSE K", send: "Передать запрос", receive: "Принять ответ SORA", soraReply: "SORA подтверждает связь с холма и просит ваше итоговое решение.", choose: "Итоговое решение", believe: "Поверить записи", requestReview: "Запросить проверку", defer: "Отложить решение", settle: "Записать и закрыть", success: "Дело QSL закрыто", failed: "Уточнение не удалось", retry: "Повторить расследование", agn: "Повтор — AGN K", qrs: "Медленнее — QRS K", leave: "В центр управления", leaveConfirm: "Расследование QSL не завершено. Выйти?", cancel: "Продолжить", confirmLeave: "Выйти", paused: "Расследование QSL приостановлено настройками", case: "Дело", errors: "Ошибки", FORMAT_INVALID: "Неверный формат сообщения", CASE_MISMATCH: "Номер дела QSL не совпадает", CALLSIGN_MISMATCH: "Ваш позывной не совпадает", QSL_REQUIRED: "Сообщение должно начинаться с QSL", SEMANTIC_UNSAFE: "Проверка смысловой безопасности не пройдена" }),
});

export const QSL_STORY_CHOICE_KEYS = Object.freeze({
  believe: "believe", "request-review": "requestReview", defer: "defer",
});

export function qslStoryLeaveRisk(run, settled = false) {
  if (!run || typeof run !== "object" || settled) return "none";
  if (run.phase === QSL_STORY_PHASES.COMPLETED) return "unsaved";
  return [QSL_STORY_PHASES.FAILED, QSL_STORY_PHASES.ABANDONED].includes(run.phase)
    ? "none" : "active";
}
